#!/usr/bin/env bash
# alloy-snmp-discover.sh — write group config + one-shot snmp-discovery.
#
# Admin object is alloy/snmp-discovery.yml: CIDR + named auths (not devices.yaml).
# Community never lands in SD. Operator pins/ignores in alloy/snmp-overrides.yml.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=fabric-nodes.sh
source "${ROOT}/scripts/fabric-nodes.sh"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "${ROOT}/.env")
  set +a
fi

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

IMAGE="${ALLOY_IMAGE:-srl-local/alloy:network-dev}"
CLAB_NET="${CLAB_NETWORK:-clab}"
AUTH_NAMES="${ALLOY_SNMP_AUTHS:-public_v2}"
# Single-group override. Empty = one group on laptop (hq), or per-site jobs on colocated.
GROUP_NAME="${ALLOY_SNMP_GROUP:-}"
[[ "${GROUP_NAME}" == "laptop" || "${GROUP_NAME}" == "colocated" ]] && GROUP_NAME=""

docker image inspect "${IMAGE}" >/dev/null 2>&1 \
  || die "image ${IMAGE} not found — run: make alloy-network-image"

mkdir -p "${ROOT}/alloy"

extract_from_image() {
  local dest="$1" img_path="$2"
  # Always refresh from the running image so fingerprinters.yml and
  # snmp-network.yml stay the same convert (stale host files invent module= names).
  info "extracting ${img_path} from ${IMAGE}"
  docker run --rm --entrypoint cat "${IMAGE}" "${img_path}" > "${dest}.tmp"
  [[ -s "${dest}.tmp" ]] || die "failed to extract ${img_path} from ${IMAGE}"
  mv -f "${dest}.tmp" "${dest}"
}

if [[ "${SKIP_SNMP_IMAGE_EXTRACT:-0}" == "1" ]]; then
  info "SKIP_SNMP_IMAGE_EXTRACT=1 — using host catalog (consolidated *_topo objects)"
  [[ -s "${ROOT}/alloy/snmp-network.yml" ]] || die "missing ${ROOT}/alloy/snmp-network.yml"
  [[ -s "${ROOT}/alloy/fingerprinters.yml" ]] || die "missing ${ROOT}/alloy/fingerprinters.yml"
else
  extract_from_image "${ROOT}/alloy/snmp-network.yml" "/etc/alloy/snmp-network.yml"
  extract_from_image "${ROOT}/alloy/fingerprinters.yml" "/etc/alloy/fingerprinters.yml"
fi

if [[ ! -f "${ROOT}/alloy/snmp-overrides.yml" ]]; then
  if [[ -f "${ROOT}/fixtures/alloy-snmp/snmp-overrides.yml" ]]; then
    cp -f "${ROOT}/fixtures/alloy-snmp/snmp-overrides.yml" "${ROOT}/alloy/snmp-overrides.yml"
  else
    echo 'overrides: []' > "${ROOT}/alloy/snmp-overrides.yml"
  fi
fi

# Older lab revisions generated address+name overrides for every SRL. Those
# overrides beat live sysName and can rename a different device after clab
# reallocates an address. Migrate only that generated file; preserve operator
# overrides.
if grep -q '^# GENERATED by scripts/render-snmp-topology-overrides.sh' \
  "${ROOT}/alloy/snmp-overrides.yml" 2>/dev/null; then
  info "removing legacy address/name topology overrides"
  echo 'overrides: []' > "${ROOT}/alloy/snmp-overrides.yml"
fi

# Discover the management network, not a pre-enumerated device list. Device
# identity comes from live SNMP sysName and modules from sysObjectID. The
# explicit CIDR setting remains useful for routed/external networks.
cidrs=()
if [[ -n "${ALLOY_SNMP_CIDRS:-}" ]]; then
  IFS=',' read -r -a _manual <<< "${ALLOY_SNMP_CIDRS}"
  cidrs=("${_manual[@]}")
else
  subnet="$(
    docker network inspect \
      -f '{{range .IPAM.Config}}{{println .Subnet}}{{end}}' \
      "${CLAB_NET}" 2>/dev/null \
      | awk '/^[0-9]+\./ { print; exit }'
  )"
  [[ -n "${subnet}" ]] || die "no IPv4 subnet for Docker network ${CLAB_NET}"
  cidrs=("${subnet}")
fi

emit_group() {
  local name="$1"
  shift
  [[ $# -gt 0 ]] || return 0
  echo "  - name: ${name}"
  echo "    cidrs:"
  for c in "$@"; do
    printf '      - %s\n' "${c}"
  done
  echo "    auths:"
  local a
  IFS=',' read -r -a _auths <<< "${AUTH_NAMES}"
  for a in "${_auths[@]}"; do
    a="$(echo "${a}" | tr -d '[:space:]')"
    [[ -n "${a}" ]] && printf '      - %s\n' "${a}"
  done
  echo "    fingerprinter: network"
}

CFG="${ROOT}/alloy/snmp-discovery.yml"
DISCOVERY_GROUP="${GROUP_NAME:-}"
if [[ -z "${DISCOVERY_GROUP}" ]]; then
  if [[ "${LAB_FABRIC_PROFILE}" == "colocated" ]]; then
    DISCOVERY_GROUP="colocated"
  else
    DISCOVERY_GROUP="hq"
  fi
fi
{
  echo "# GENERATED by scripts/alloy-snmp-discover.sh — live management subnet. Do not put communities here."
  echo "# Pins/ignores: alloy/snmp-overrides.yml (kept across regenerates)."
  echo "# Identity comes from SNMP sysName; modules come from sysObjectID fingerprinting."
  echo "groups:"
  emit_group "${DISCOVERY_GROUP}" "${cidrs[@]}"
} > "${CFG}"
[[ -s "${CFG}" ]] && grep -q 'cidrs:' "${CFG}" || die "no CIDRs — start the fabric or set ALLOY_SNMP_CIDRS="
info "wrote ${CFG}"
grep -E 'name:|cidrs:|/' "${CFG}" || true

uid="$(id -u)"
gid="$(id -g)"

docker run --rm --network "${CLAB_NET}" --user "${uid}:${gid}" \
  -v "${ROOT}/alloy/snmp-network.yml:/etc/alloy/snmp-network.yml:ro" \
  -v "${ROOT}/alloy/fingerprinters.yml:/etc/alloy/fingerprinters.yml:ro" \
  -v "${CFG}:/etc/alloy/snmp-discovery.yml:ro" \
  -v "${ROOT}/alloy/snmp-overrides.yml:/etc/alloy/snmp-overrides.yml:ro" \
  -v "${ROOT}/alloy:/out" \
  --entrypoint /usr/bin/snmp-discovery \
  "${IMAGE}" \
  --config /etc/alloy/snmp-discovery.yml \
  --overrides /etc/alloy/snmp-overrides.yml \
  --snmp-config /etc/alloy/snmp-network.yml \
  --fingerprinters /etc/alloy/fingerprinters.yml \
  --out-alloy /out/snmp-targets.yml \
  --out-file-sd /out/snmp-file-sd.json

info "wrote alloy/snmp-targets.yml and alloy/snmp-file-sd.json"

python3 "${ROOT}/scripts/render-device-join.py" \
  || info "device-join catalog skipped (clients may be down)"
