#!/usr/bin/env bash
# Colocated-only: run topology-exporter in Alloy-OTLP glue mode and retarget
# the Alloy topology scrape off Grafana. Does not recycle ktranslate.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export KUBECONFIG="${KUBECONFIG:-/etc/rancher/k3s/k3s.yaml}"
export COLLECTOR_RUNTIME=k3s
export LAB_FABRIC_PROFILE=colocated
export TOPOLOGY_EXPORTER_OTLP="${TOPOLOGY_EXPORTER_OTLP:-http://127.0.0.1:9100}"
BIN="${TOPOLOGY_EXPORTER_BIN:-${ROOT}/topology-exporter/topology-exporter-linux-amd64}"
CFG="${ROOT}/topology-exporter/config-alloy-glue.yaml"
CATALOG="${ROOT}/alloy/snmp-targets.yml"
UNIT=/etc/systemd/system/topology-exporter-glue.service

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "${ROOT}/.env")
  set +a
fi

info() { echo "==> [topo-glue] $*"; }

upsert_env() {
  local key="$1" val="$2" file="${ROOT}/.env"
  [[ -f "${file}" ]] || { echo "ERROR: missing ${file}" >&2; exit 1; }
  if grep -qE "^${key}=" "${file}"; then
    sed -i "s|^${key}=.*|${key}=${val}|" "${file}"
  else
    printf '\n%s=%s\n' "${key}" "${val}" >> "${file}"
  fi
}

[[ -x "${BIN}" ]] || { echo "ERROR: missing binary ${BIN}" >&2; exit 1; }
[[ -f "${CFG}" ]] || { echo "ERROR: missing ${CFG}" >&2; exit 1; }
[[ -s "${CATALOG}" ]] || { echo "ERROR: empty catalog ${CATALOG}" >&2; exit 1; }

upsert_env LAB_ALLOY_SNMP 1
upsert_env LAB_ALLOY_SNMP_TOPOLOGY 1
upsert_env LAB_ALLOY_SNMP_TOPOLOGY_INTERVAL "${LAB_ALLOY_SNMP_TOPOLOGY_INTERVAL:-2m}"
upsert_env TOPOLOGY_EXPORTER_OTLP "${TOPOLOGY_EXPORTER_OTLP}"
export LAB_ALLOY_SNMP=1
export LAB_ALLOY_SNMP_TOPOLOGY=1
export LAB_ALLOY_SNMP_TOPOLOGY_INTERVAL="${LAB_ALLOY_SNMP_TOPOLOGY_INTERVAL:-2m}"
export COLLECTOR_RUNTIME=k3s
export TOPOLOGY_EXPORTER_OTLP

install -d /etc/topology-exporter
install -d -m 0755 /var/lib/topology-exporter
if [[ -f /tmp/network-topology-exporter-snapshot.json && ! -f /var/lib/topology-exporter/snapshot.json ]]; then
  mv /tmp/network-topology-exporter-snapshot.json /var/lib/topology-exporter/snapshot.json
fi
install -m 0644 "${CFG}" /etc/topology-exporter/config.yaml
# Catalog is a live file; bind via symlink so discovery updates are seen after restart.
ln -sfn "${CATALOG}" /etc/topology-exporter/catalog.yml
ALIASES="${ROOT}/topology-exporter/aliases-colocated.yml"
if [[ -f "${ALIASES}" ]]; then
  install -m 0644 "${ALIASES}" /etc/topology-exporter/aliases.yml
fi
systemctl stop topology-exporter-glue.service 2>/dev/null || true
install -m 0755 "${BIN}" /usr/local/bin/topology-exporter

cat > "${UNIT}" <<EOF
[Unit]
Description=network-topology-exporter (Alloy OTLP glue)
After=network.target

[Service]
Type=simple
StateDirectory=topology-exporter
ExecStart=/usr/local/bin/topology-exporter --config.file=/etc/topology-exporter/config.yaml --web.listen-address=:9100 --log.level=info
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable topology-exporter-glue.service
systemctl restart topology-exporter-glue.service
sleep 1
systemctl --no-pager --full status topology-exporter-glue.service | head -25
curl -sS -m 3 http://127.0.0.1:9100/healthz || true
echo

info "render Alloy topology scrape → ${TOPOLOGY_EXPORTER_OTLP} (patch live CM; do not regenerate ktranslate)"
bash "${ROOT}/scripts/render-snmp-topology-overrides.sh"
cd "${ROOT}"
export COLLECTOR_RUNTIME=k3s
export LAB_ALLOY_SNMP=1
export LAB_ALLOY_SNMP_TOPOLOGY=1
export TOPOLOGY_EXPORTER_OTLP
bash "${ROOT}/scripts/render-alloy-snmp-scrape.sh"
python3 - <<'PY'
from pathlib import Path
import subprocess
prefix = Path("/opt/network-o11y-demo/local/alloy/config.alloy").read_text()
new = Path("/opt/network-o11y-demo/local/alloy/snmp-scrape.generated.alloy").read_text()
live = subprocess.check_output(
    ["kubectl", "-n", "network-lab", "get", "cm", "alloy-config", "-o", "jsonpath={.data.config\\.alloy}"],
    text=True,
)
scrape = live.find("// GENERATED by scripts/render-alloy-snmp-scrape.sh")
trap = live.find("// GENERATED by scripts/render-alloy-snmp-trap.sh")
if trap < 0:
    raise SystemExit("trap marker not found")
mid_from = -1
for marker in (
    "// GENERATED by scripts/render-alloy-otlp-export.sh",
    "// GENERATED by scripts/render-alloy-remotecfg.sh",
    "// GENERATED by scripts/render-alloy-netflow.sh",
):
    i = live.find(marker)
    if i >= 0 and (scrape < 0 or i < scrape):
        mid_from = i
        break
middle = live[mid_from:scrape] if mid_from >= 0 and scrape > mid_from else ""
merged = prefix.rstrip() + "\n\n" + middle + new.rstrip() + "\n\n" + live[trap:]
Path("/tmp/alloy-config.alloy").write_text(merged)
if 'otelcol.exporter.otlphttp "topology"' not in merged:
    raise SystemExit("topology exporter block missing")
if "keep_gnmic_topology" not in merged:
    raise SystemExit("gnmic topology fork missing")
if 'prometheus.scrape "topology_exporter_graph"' not in merged:
    raise SystemExit("topology exporter /metrics scrape missing")
print(f"patched river prefix+scrape -> {len(merged)} bytes")
PY
kubectl -n network-lab create configmap alloy-config --from-file=config.alloy=/tmp/alloy-config.alloy -o yaml --dry-run=client | kubectl apply -f -
kubectl -n network-lab delete pod -l app=alloy --wait=true --timeout=90s || true
kubectl -n network-lab rollout status deploy/alloy --timeout=180s

info "confirm river forks topology off Grafana"
kubectl -n network-lab get cm alloy-config -o jsonpath='{.data.config\.alloy}' \
  | grep -n -E 'otlphttp "topology"|127.0.0.1:9100|alloy_snmp_topology' | head -20

info "exporter listeners / recent log"
ss -lntup | grep ':9100' || true
journalctl -u topology-exporter-glue -n 30 --no-pager || true
