#!/usr/bin/env bash
# alloy-snmp-discover.sh — write group config + one-shot snmp-discovery.
#
# Admin object is alloy/snmp-discovery.yml: CIDR + named auths (not devices.yaml).
# Community never lands in SD. Operator pins/ignores in alloy/snmp-overrides.yml.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=fabric-nodes.sh
source "${ROOT}/scripts/fabric-nodes.sh"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "${ROOT}/.env")
  set +a
fi

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

IMAGE="${ALLOY_IMAGE:-srl-local/alloy:network-dev}"
CLAB_NET="${CLAB_NETWORK:-clab}"
AUTH_NAMES="${ALLOY_SNMP_AUTHS:-public_v2}"
GROUP_NAME="${ALLOY_SNMP_GROUP:-${LAB_FABRIC_PROFILE:-srl-hq}}"
[[ "${GROUP_NAME}" == "laptop" ]] && GROUP_NAME=srl-hq

docker image inspect "${IMAGE}" >/dev/null 2>&1 \
  || die "image ${IMAGE} not found — run: make alloy-network-image"

mkdir -p "${ROOT}/alloy"

extract_from_image() {
  local dest="$1" img_path="$2"
  if [[ -f "${dest}" ]]; then
    return 0
  fi
  info "extracting ${img_path} from ${IMAGE}"
  docker run --rm --entrypoint cat "${IMAGE}" "${img_path}" > "${dest}"
  [[ -s "${dest}" ]] || die "failed to extract ${img_path} from ${IMAGE}"
}

extract_from_image "${ROOT}/alloy/snmp-network.yml" "/etc/alloy/snmp-network.yml"
extract_from_image "${ROOT}/alloy/fingerprinters.yml" "/etc/alloy/fingerprinters.yml"

if [[ ! -f "${ROOT}/alloy/snmp-overrides.yml" ]]; then
  if [[ -f "${ROOT}/fixtures/alloy-snmp/snmp-overrides.yml" ]]; then
    cp -f "${ROOT}/fixtures/alloy-snmp/snmp-overrides.yml" "${ROOT}/alloy/snmp-overrides.yml"
  else
    echo 'overrides: []' > "${ROOT}/alloy/snmp-overrides.yml"
  fi
fi

cidrs=()
if [[ -n "${ALLOY_SNMP_CIDRS:-}" ]]; then
  IFS=',' read -r -a cidrs <<< "${ALLOY_SNMP_CIDRS}"
else
  for n in "${SRL_NODES[@]}"; do
    ip="$(docker inspect -f "{{(index .NetworkSettings.Networks \"${CLAB_NET}\").IPAddress}}" "$n" 2>/dev/null || true)"
    if [[ -n "${ip}" && "${ip}" != "<no value>" ]]; then
      cidrs+=("${ip}/32")
    fi
  done
fi
[[ ${#cidrs[@]} -gt 0 ]] || die "no CIDRs — start the fabric or set ALLOY_SNMP_CIDRS="

CFG="${ROOT}/alloy/snmp-discovery.yml"
{
  echo "# GENERATED by scripts/alloy-snmp-discover.sh — live CIDRs. Do not put communities here."
  echo "# Pins/ignores: alloy/snmp-overrides.yml (kept across regenerates)."
  echo "groups:"
  echo "  - name: ${GROUP_NAME}"
  echo "    cidrs:"
  for c in "${cidrs[@]}"; do
    printf '      - %s\n' "${c}"
  done
  echo "    auths:"
  IFS=',' read -r -a _auths <<< "${AUTH_NAMES}"
  for a in "${_auths[@]}"; do
    a="$(echo "${a}" | tr -d '[:space:]')"
    [[ -n "${a}" ]] && printf '      - %s\n' "${a}"
  done
  echo "    fingerprinter: network"
} > "${CFG}"
info "wrote ${CFG} (group=${GROUP_NAME})"

uid="$(id -u)"
gid="$(id -g)"

docker run --rm --network "${CLAB_NET}" --user "${uid}:${gid}" \
  -v "${ROOT}/alloy/snmp-network.yml:/etc/alloy/snmp-network.yml:ro" \
  -v "${ROOT}/alloy/fingerprinters.yml:/etc/alloy/fingerprinters.yml:ro" \
  -v "${CFG}:/etc/alloy/snmp-discovery.yml:ro" \
  -v "${ROOT}/alloy/snmp-overrides.yml:/etc/alloy/snmp-overrides.yml:ro" \
  -v "${ROOT}/alloy:/out" \
  --entrypoint /usr/bin/snmp-discovery \
  "${IMAGE}" \
  --config /etc/alloy/snmp-discovery.yml \
  --overrides /etc/alloy/snmp-overrides.yml \
  --snmp-config /etc/alloy/snmp-network.yml \
  --fingerprinters /etc/alloy/fingerprinters.yml \
  --out-alloy /out/snmp-targets.yml \
  --out-file-sd /out/snmp-file-sd.json

info "wrote alloy/snmp-targets.yml and alloy/snmp-file-sd.json"
