#!/usr/bin/env bash
# alloy-snmp-discover.sh — write group config + one-shot snmp-discovery.
#
# Admin object is alloy/snmp-discovery.yml: CIDR + named auths (not devices.yaml).
# Community never lands in SD. Operator pins/ignores in alloy/snmp-overrides.yml.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=fabric-nodes.sh
source "${ROOT}/scripts/fabric-nodes.sh"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "${ROOT}/.env")
  set +a
fi

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

IMAGE="${ALLOY_IMAGE:-srl-local/alloy:network-dev}"
CLAB_NET="${CLAB_NETWORK:-clab}"
AUTH_NAMES="${ALLOY_SNMP_AUTHS:-public_v2}"
# Single-group override. Empty = one group on laptop (hq), or per-site jobs on colocated.
GROUP_NAME="${ALLOY_SNMP_GROUP:-}"
[[ "${GROUP_NAME}" == "laptop" || "${GROUP_NAME}" == "colocated" ]] && GROUP_NAME=""

docker image inspect "${IMAGE}" >/dev/null 2>&1 \
  || die "image ${IMAGE} not found — run: make alloy-network-image"

mkdir -p "${ROOT}/alloy"

extract_from_image() {
  local dest="$1" img_path="$2"
  # Always refresh from the running image so fingerprinters.yml and
  # snmp-network.yml stay the same convert (stale host files invent module= names).
  info "extracting ${img_path} from ${IMAGE}"
  docker run --rm --entrypoint cat "${IMAGE}" "${img_path}" > "${dest}.tmp"
  [[ -s "${dest}.tmp" ]] || die "failed to extract ${img_path} from ${IMAGE}"
  mv -f "${dest}.tmp" "${dest}"
}

extract_from_image "${ROOT}/alloy/snmp-network.yml" "/etc/alloy/snmp-network.yml"
extract_from_image "${ROOT}/alloy/fingerprinters.yml" "/etc/alloy/fingerprinters.yml"

if [[ ! -f "${ROOT}/alloy/snmp-overrides.yml" ]]; then
  if [[ -f "${ROOT}/fixtures/alloy-snmp/snmp-overrides.yml" ]]; then
    cp -f "${ROOT}/fixtures/alloy-snmp/snmp-overrides.yml" "${ROOT}/alloy/snmp-overrides.yml"
  else
    echo 'overrides: []' > "${ROOT}/alloy/snmp-overrides.yml"
  fi
fi

node_ip() {
  docker inspect -f "{{(index .NetworkSettings.Networks \"${CLAB_NET}\").IPAddress}}" "$1" 2>/dev/null || true
}

# site → space-separated cidrs (hq / branch1 / branch2). One discovery job per site
# on colocated; laptop/snmp-min is a single hq job. ALLOY_SNMP_GROUP / ALLOY_SNMP_CIDRS
# force one job (escape hatch).
hq_cidrs=()
branch1_cidrs=()
branch2_cidrs=()
if [[ -n "${ALLOY_SNMP_CIDRS:-}" ]]; then
  IFS=',' read -r -a _manual <<< "${ALLOY_SNMP_CIDRS}"
  hq_cidrs=("${_manual[@]}")
else
  for n in "${SRL_NODES[@]}"; do
    ip="$(node_ip "$n")"
    [[ -n "${ip}" && "${ip}" != "<no value>" ]] || continue
    case "$(fabric_site_for_node "$n")" in
      branch1) branch1_cidrs+=("${ip}/32") ;;
      branch2) branch2_cidrs+=("${ip}/32") ;;
      *) hq_cidrs+=("${ip}/32") ;;
    esac
  done
fi

emit_group() {
  local name="$1"
  shift
  [[ $# -gt 0 ]] || return 0
  echo "  - name: ${name}"
  echo "    cidrs:"
  for c in "$@"; do
    printf '      - %s\n' "${c}"
  done
  echo "    auths:"
  local a
  IFS=',' read -r -a _auths <<< "${AUTH_NAMES}"
  for a in "${_auths[@]}"; do
    a="$(echo "${a}" | tr -d '[:space:]')"
    [[ -n "${a}" ]] && printf '      - %s\n' "${a}"
  done
  echo "    fingerprinter: network"
}

CFG="${ROOT}/alloy/snmp-discovery.yml"
{
  echo "# GENERATED by scripts/alloy-snmp-discover.sh — live CIDRs. Do not put communities here."
  echo "# Pins/ignores: alloy/snmp-overrides.yml (kept across regenerates)."
  echo "# snmp_group on targets = discovery job name (site chunk on colocated)."
  echo "groups:"
  if [[ -n "${GROUP_NAME}" ]]; then
    all_cidrs=("${hq_cidrs[@]}" "${branch1_cidrs[@]}" "${branch2_cidrs[@]}")
    emit_group "${GROUP_NAME}" "${all_cidrs[@]}"
  elif [[ "${LAB_FABRIC_PROFILE}" == "colocated" ]]; then
    [[ ${#hq_cidrs[@]} -gt 0 ]] && emit_group hq "${hq_cidrs[@]}"
    [[ ${#branch1_cidrs[@]} -gt 0 ]] && emit_group branch1 "${branch1_cidrs[@]}"
    [[ ${#branch2_cidrs[@]} -gt 0 ]] && emit_group branch2 "${branch2_cidrs[@]}"
  else
    emit_group hq "${hq_cidrs[@]}"
  fi
} > "${CFG}"
[[ -s "${CFG}" ]] && grep -q 'cidrs:' "${CFG}" || die "no CIDRs — start the fabric or set ALLOY_SNMP_CIDRS="
info "wrote ${CFG}"
grep -E 'name:|cidrs:|/' "${CFG}" || true

uid="$(id -u)"
gid="$(id -g)"

docker run --rm --network "${CLAB_NET}" --user "${uid}:${gid}" \
  -v "${ROOT}/alloy/snmp-network.yml:/etc/alloy/snmp-network.yml:ro" \
  -v "${ROOT}/alloy/fingerprinters.yml:/etc/alloy/fingerprinters.yml:ro" \
  -v "${CFG}:/etc/alloy/snmp-discovery.yml:ro" \
  -v "${ROOT}/alloy/snmp-overrides.yml:/etc/alloy/snmp-overrides.yml:ro" \
  -v "${ROOT}/alloy:/out" \
  --entrypoint /usr/bin/snmp-discovery \
  "${IMAGE}" \
  --config /etc/alloy/snmp-discovery.yml \
  --overrides /etc/alloy/snmp-overrides.yml \
  --snmp-config /etc/alloy/snmp-network.yml \
  --fingerprinters /etc/alloy/fingerprinters.yml \
  --out-alloy /out/snmp-targets.yml \
  --out-file-sd /out/snmp-file-sd.json

info "wrote alloy/snmp-targets.yml and alloy/snmp-file-sd.json"

# Catalog state can keep a stale snmp_group when a probe misses. Re-stamp from
# fabric site so dashboards see hq / branch1 / branch2, not leftover "colocated".
if [[ "${LAB_FABRIC_PROFILE}" == "colocated" && -z "${GROUP_NAME}" ]]; then
python3 - "${ROOT}/alloy" <<'PY'
from pathlib import Path
import sys

site = {
    "spine1": "hq",
    "leaf1": "hq",
    "leaf2": "hq",
    "client1": "hq",
    "client2": "hq",
    "leaf-br1": "branch1",
    "client-br1": "branch1",
    "leaf-br2": "branch2",
    "client-br2": "branch2",
}
alloy = Path(sys.argv[1])
changed = 0
for path in (
    alloy / "snmp-targets.yml",
    alloy / "snmp-targets-cold.yml",
    alloy / "snmp-targets-topology.yml",
):
    if not path.is_file():
        continue
    lines = path.read_text(encoding="utf-8").splitlines()
    current = None
    out = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("device_name:"):
            current = stripped.split(":", 1)[1].strip()
        if stripped.startswith("snmp_group:") and current in site:
            indent = line[: len(line) - len(line.lstrip())]
            new = f"{indent}snmp_group: {site[current]}"
            if new != line:
                changed += 1
            line = new
        out.append(line)
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"stamped snmp_group from fabric site ({changed} row(s))")
PY
fi

python3 "${ROOT}/scripts/render-device-join.py" \
  || info "device-join catalog skipped (clients may be down)"
