#!/usr/bin/env bash
# Compute per-container Docker memory limits from host MemAvailable and the
# number of SNMP pollers, then write compose-limits.generated.yaml.
#
# Limits are per-container (Docker has no project-wide cap). The script sizes
# caps so their sum stays within a configurable fraction of available RAM,
# with SNMP pollers receiving the largest share -- up to 4G each, which matches
# a common 4 vCPU / 8 GiB trial host running one poller plus alloy/flow/syslog.
#
# Layout detection:
#   - groups/*.env present  -> multicontainer (ktranslate_snmp_<group> per file)
#   - otherwise             -> main branch single service (ktranslate_snmp)
#
# Usage:
#   ./scripts/compute-limits.sh           # write compose-limits.generated.yaml
#   ./scripts/compute-limits.sh --dry-run # print plan only
#
# Environment (optional, typically set in .env):
#   MEM_LIMITS=off              Skip generation; write a no-op overlay
#   MEM_BUDGET_FRACTION=0.80    Fraction of MemAvailable for the stack (default 0.80)
#   MEM_SNMP_MAX=4g             Per-poller ceiling (default 4g)
#   MEM_SNMP_MIN=512m           Per-poller floor when budget allows (default 512m)
#   MEM_SNMP_LIMIT=             Hard override for every SNMP poller (skip math)
#   MEM_FLOW_LIMIT=             Hard override for ktranslate_flow
#   MEM_ALLOY_LIMIT=            Hard override for alloy
#   MEM_SYSLOG_LIMIT=           Hard override for ktranslate_syslog

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${REPO_ROOT}"

OUT="${REPO_ROOT}/compose-limits.generated.yaml"
DRY_RUN=0

for arg in "$@"; do
  case "${arg}" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help)
      sed -n '2,28p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: ${arg}" >&2
      exit 1
      ;;
  esac
done

# Load .env for MEM_* overrides without requiring docker compose interpolation.
if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

if [[ "${MEM_LIMITS:-}" == "off" ]]; then
  echo "MEM_LIMITS=off -- skipping memory limit generation"
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    echo "dry-run: would write an empty limits overlay"
    exit 0
  fi
  cat > "${OUT}" <<'EOF'
# GENERATED by scripts/compute-limits.sh -- limits disabled (MEM_LIMITS=off).
# compose merge keeps base service definitions unchanged.
services: {}
EOF
  echo "wrote ${OUT} (no limits applied)"
  exit 0
fi

# --- helpers -----------------------------------------------------------------

parse_mem_to_mb() {
  local raw="${1,,}"
  raw="${raw// /}"
  if [[ "${raw}" =~ ^([0-9]+)([kmg])?$ ]]; then
    local n="${BASH_REMATCH[1]}"
    local u="${BASH_REMATCH[2]:-m}"
    case "${u}" in
      k) echo $(( n / 1024 )) ;;
      m) echo "${n}" ;;
      g) echo $(( n * 1024 )) ;;
    esac
    return 0
  fi
  echo "ERROR: invalid memory value '${1}'" >&2
  exit 1
}

fmt_mb() {
  local mb="$1"
  if (( mb >= 1024 && mb % 1024 == 0 )); then
    echo "$(( mb / 1024 ))g"
  else
    echo "${mb}m"
  fi
}

clamp_mb() {
  local val="$1"
  local min="$2"
  local max="$3"
  if (( val < min )); then val="${min}"; fi
  if (( val > max )); then val="${max}"; fi
  echo "${val}"
}

read_available_mb() {
  local avail total docker_b

  # Linux / WSL
  if [[ -r /proc/meminfo ]]; then
    avail=$(awk '/^MemAvailable:/ {print int($2/1024)}' /proc/meminfo)
    if [[ -n "${avail}" && "${avail}" -gt 0 ]]; then
      echo "${avail}"
      return 0
    fi
    total=$(awk '/^MemTotal:/ {print int($2/1024)}' /proc/meminfo)
    if [[ -n "${total}" && "${total}" -gt 0 ]]; then
      echo $(( total * 80 / 100 ))
      return 0
    fi
  fi

  # Docker Desktop VM budget (macOS / Windows) — best proxy for compose limits
  if command -v docker >/dev/null 2>&1; then
    docker_b=$(docker info --format '{{.MemTotal}}' 2>/dev/null || true)
    if [[ "${docker_b}" =~ ^[0-9]+$ && "${docker_b}" -gt 0 ]]; then
      echo $(( docker_b / 1024 / 1024 ))
      return 0
    fi
  fi

  # macOS host RAM (conservative — not all RAM is given to Docker)
  if [[ "$(uname -s)" == "Darwin" ]]; then
    total=$(sysctl -n hw.memsize 2>/dev/null || true)
    if [[ "${total}" =~ ^[0-9]+$ && "${total}" -gt 0 ]]; then
      echo $(( total / 1024 / 1024 * 50 / 100 ))
      return 0
    fi
  fi

  echo "ERROR: could not determine host memory (set MEM_LIMITS=off in .env to skip)" >&2
  exit 1
}

emit_service_limit() {
  local svc="$1"
  local mb="$2"
  local lim
  lim="$(fmt_mb "${mb}")"
  cat <<EOF
  ${svc}:
    mem_limit: ${lim}
    memswap_limit: ${lim}
EOF
}

# --- inputs ------------------------------------------------------------------

BUDGET_FRACTION="${MEM_BUDGET_FRACTION:-0.80}"
SNMP_MAX_MB="$(parse_mem_to_mb "${MEM_SNMP_MAX:-4g}")"
SNMP_MIN_MB="$(parse_mem_to_mb "${MEM_SNMP_MIN:-512m}")"
FLOW_MAX_MB="$(parse_mem_to_mb "${MEM_FLOW_MAX:-1536m}")"
FLOW_MIN_MB="$(parse_mem_to_mb "${MEM_FLOW_MIN:-256m}")"
ALLOY_MAX_MB="$(parse_mem_to_mb "${MEM_ALLOY_MAX:-1024m}")"
ALLOY_MIN_MB="$(parse_mem_to_mb "${MEM_ALLOY_MIN:-256m}")"
SYSLOG_MAX_MB="$(parse_mem_to_mb "${MEM_SYSLOG_MAX:-512m}")"
SYSLOG_MIN_MB="$(parse_mem_to_mb "${MEM_SYSLOG_MIN:-128m}")"

if ! awk -v f="${BUDGET_FRACTION}" 'BEGIN { exit !(f > 0 && f <= 1) }'; then
  echo "ERROR: MEM_BUDGET_FRACTION must be > 0 and <= 1 (got '${BUDGET_FRACTION}')" >&2
  exit 1
fi

SNMP_SERVICES=()
shopt -s nullglob
GROUP_FILES=(groups/*.env)
shopt -u nullglob

if (( ${#GROUP_FILES[@]} > 0 )); then
  for env_file in "${GROUP_FILES[@]}"; do
    group="$(awk -F= '/^GROUP=/{print $2; exit}' "${env_file}")"
    [[ -z "${group}" ]] && continue
    SNMP_SERVICES+=("ktranslate_snmp_${group}")
  done
else
  # main-branch single-poller layout
  SNMP_SERVICES=("ktranslate_snmp")
fi

NUM_SNMP="${#SNMP_SERVICES[@]}"
if [[ "${NUM_SNMP}" -eq 0 ]]; then
  echo "WARN: no SNMP poller services discovered -- SNMP limits will not be emitted" >&2
fi

AVAIL_MB="$(read_available_mb)"
BUDGET_MB="$(awk -v a="${AVAIL_MB}" -v f="${BUDGET_FRACTION}" 'BEGIN { printf "%d", a * f }')"

# --- sizing ------------------------------------------------------------------

if [[ -n "${MEM_ALLOY_LIMIT:-}" ]]; then
  ALLOY_MB="$(parse_mem_to_mb "${MEM_ALLOY_LIMIT}")"
else
  ALLOY_MB="$(awk -v b="${BUDGET_MB}" 'BEGIN { printf "%d", b * 0.10 }')"
  ALLOY_MB="$(clamp_mb "${ALLOY_MB}" "${ALLOY_MIN_MB}" "${ALLOY_MAX_MB}")"
fi

if [[ -n "${MEM_FLOW_LIMIT:-}" ]]; then
  FLOW_MB="$(parse_mem_to_mb "${MEM_FLOW_LIMIT}")"
else
  FLOW_MB="$(awk -v b="${BUDGET_MB}" 'BEGIN { printf "%d", b * 0.12 }')"
  FLOW_MB="$(clamp_mb "${FLOW_MB}" "${FLOW_MIN_MB}" "${FLOW_MAX_MB}")"
fi

if [[ -n "${MEM_SYSLOG_LIMIT:-}" ]]; then
  SYSLOG_MB="$(parse_mem_to_mb "${MEM_SYSLOG_LIMIT}")"
else
  SYSLOG_MB="$(awk -v b="${BUDGET_MB}" 'BEGIN { printf "%d", b * 0.06 }')"
  SYSLOG_MB="$(clamp_mb "${SYSLOG_MB}" "${SYSLOG_MIN_MB}" "${SYSLOG_MAX_MB}")"
fi

BASE_MB=$(( ALLOY_MB + FLOW_MB + SYSLOG_MB ))
SNMP_POOL_MB=$(( BUDGET_MB - BASE_MB ))

if (( SNMP_POOL_MB < 0 )); then
  echo "ERROR: host budget (${BUDGET_MB}M) is smaller than base services (${BASE_MB}M)" >&2
  echo "       MemAvailable~$(fmt_mb "${AVAIL_MB}") -- add RAM or set MEM_LIMITS=off" >&2
  exit 1
fi

BASE_MIN_MB=$(( ALLOY_MIN_MB + FLOW_MIN_MB + SYSLOG_MIN_MB ))

if [[ -n "${MEM_SNMP_LIMIT:-}" ]]; then
  SNMP_EACH_MB="$(parse_mem_to_mb "${MEM_SNMP_LIMIT}")"
elif (( NUM_SNMP == 0 )); then
  SNMP_EACH_MB=0
else
  SNMP_NEED_MB=$(( SNMP_MAX_MB * NUM_SNMP ))
  # When the host can afford it, give each poller the full ceiling (4G by default)
  # before sizing base services -- matches 8 GiB / single-poller trial deployments.
  if (( SNMP_NEED_MB + BASE_MIN_MB <= BUDGET_MB )); then
    SNMP_EACH_MB="${SNMP_MAX_MB}"
    BASE_BUDGET_MB=$(( BUDGET_MB - SNMP_NEED_MB ))
    ALLOY_MB="$(awk -v b="${BASE_BUDGET_MB}" 'BEGIN { printf "%d", b * 0.44 }')"
    ALLOY_MB="$(clamp_mb "${ALLOY_MB}" "${ALLOY_MIN_MB}" "${ALLOY_MAX_MB}")"
    FLOW_MB="$(awk -v b="${BASE_BUDGET_MB}" 'BEGIN { printf "%d", b * 0.38 }')"
    FLOW_MB="$(clamp_mb "${FLOW_MB}" "${FLOW_MIN_MB}" "${FLOW_MAX_MB}")"
    SYSLOG_MB=$(( BASE_BUDGET_MB - ALLOY_MB - FLOW_MB ))
    SYSLOG_MB="$(clamp_mb "${SYSLOG_MB}" "${SYSLOG_MIN_MB}" "${SYSLOG_MAX_MB}")"
    BASE_MB=$(( ALLOY_MB + FLOW_MB + SYSLOG_MB ))
  else
    SNMP_EACH_MB=$(( SNMP_POOL_MB / NUM_SNMP ))
    SNMP_EACH_MB="$(clamp_mb "${SNMP_EACH_MB}" "${SNMP_MIN_MB}" "${SNMP_MAX_MB}")"
  fi
fi

TOTAL_CAP_MB=$(( BASE_MB + SNMP_EACH_MB * NUM_SNMP ))

# --- report ------------------------------------------------------------------

printf 'Host MemAvailable: ~%s\n' "$(fmt_mb "${AVAIL_MB}")"
printf 'Stack budget:      ~%s (%s of available)\n' "$(fmt_mb "${BUDGET_MB}")" "${BUDGET_FRACTION}"
printf 'SNMP pollers:      %d (max %s each)\n' "${NUM_SNMP}" "$(fmt_mb "${SNMP_MAX_MB}")"
echo
printf '  %-28s %s\n' "alloy" "$(fmt_mb "${ALLOY_MB}")"
printf '  %-28s %s\n' "ktranslate_flow" "$(fmt_mb "${FLOW_MB}")"
printf '  %-28s %s\n' "ktranslate_syslog" "$(fmt_mb "${SYSLOG_MB}")"
for svc in "${SNMP_SERVICES[@]}"; do
  printf '  %-28s %s\n' "${svc}" "$(fmt_mb "${SNMP_EACH_MB}")"
done
echo
printf '  Total container caps:     ~%s\n' "$(fmt_mb "${TOTAL_CAP_MB}")"

if (( NUM_SNMP > 0 && SNMP_EACH_MB < SNMP_MIN_MB )); then
  echo
  echo "WARN: per-poller limit ($(fmt_mb "${SNMP_EACH_MB}")) is below minimum ($(fmt_mb "${SNMP_MIN_MB}")) -- host may be undersized" >&2
fi

if (( NUM_SNMP == 1 && SNMP_EACH_MB >= 3584 )); then
  echo "  (single-poller trial sizing -- SNMP poller near the 4G ceiling)"
fi

if (( DRY_RUN == 1 )); then
  echo
  echo "dry-run: not writing ${OUT}"
  exit 0
fi

# --- write overlay -----------------------------------------------------------

{
  cat <<EOF
# GENERATED by scripts/compute-limits.sh -- do not edit by hand.
# Regenerated on each \`make up\` (or \`make limits\`).
services:
EOF
  emit_service_limit "alloy" "${ALLOY_MB}"
  emit_service_limit "ktranslate_flow" "${FLOW_MB}"
  emit_service_limit "ktranslate_syslog" "${SYSLOG_MB}"
  for svc in "${SNMP_SERVICES[@]}"; do
    emit_service_limit "${svc}" "${SNMP_EACH_MB}"
  done
} > "${OUT}"

echo
echo "wrote ${OUT}"
