#!/usr/bin/env python3
"""Render k8s/ktranslate-golden manifests from local/ golden path (KtransToGrafana).

Runs generate-groups.sh then emits Kubernetes YAML aligned with compose-base.yaml.

Usage:
  python3 local/scripts/generate-k8s-telemetry.py
  python3 local/scripts/generate-k8s-telemetry.py --dry-run
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOCAL = ROOT / "local"
OUT = ROOT / "k8s" / "ktranslate-golden"
TEMPLATES = LOCAL / "templates" / "k8s"
NAMESPACE = "network-lab"
KTRANSLATE_IMAGE = "quay.io/kentik/ktranslate:latest"
STATE_HOST_PATH = "/opt/network-o11y-demo/local/state"
# hostNetwork pods cannot share host ports — avoid RollingUpdate (stuck Pending duplicates).
HOST_NETWORK_STRATEGY = """  strategy:
    type: Recreate
"""


def run_generate_groups() -> None:
    subprocess.run(["bash", str(LOCAL / "scripts" / "generate-groups.sh")], cwd=LOCAL, check=True)
    subprocess.run(["bash", str(LOCAL / "scripts" / "write-compose-host-env.sh")], cwd=LOCAL, check=True)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_ktrans_host() -> str:
    # Always resolve from .env / host-id.sh on this machine — never a stale
    # compose-host.generated.env from another laptop checked into the tree.
    return subprocess.check_output(
        ["bash", str(LOCAL / "scripts" / "host-id.sh")], text=True
    ).strip()


def write_manifest(name: str, body: str, dry_run: bool) -> None:
    header = (
        "# GENERATED by local/scripts/generate-k8s-telemetry.py — do not edit by hand.\n"
        "# Re-run: python3 local/scripts/generate-k8s-telemetry.py\n"
    )
    content = header + body.lstrip()
    dest = OUT / name
    if dry_run:
        print(f"--- {dest.name} ({len(content)} bytes)")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    print(f"wrote {dest.relative_to(ROOT)}")


def yaml_block(text: str, indent: int = 4) -> str:
    pad = " " * indent
    return "\n".join(pad + line for line in text.rstrip().splitlines())


def load_poller_configs() -> list[tuple[str, str]]:
    configs = sorted((LOCAL / "config").glob("poller-*.yaml"))
    if not configs:
        raise SystemExit("no poller configs — cp groups/srl-hq.env.sample groups/srl-hq.env && make generate")
    return [(p.stem.replace("poller-", ""), read_text(p)) for p in configs]


def otel_service_name(base: str, host: str) -> str:
    return f"{base}-{host}" if host else base


def ktranslate_env(base: str, host: str) -> str:
    return f"""          env:
            - name: OTEL_SERVICE_NAME
              value: {otel_service_name(base, host)}
            - name: OTEL_EXPORTER_OTLP_COMPRESSION
              value: gzip"""


def patch_gnmic_config(raw: str) -> str:
    hosts = LOCAL / "dnsmasq" / "hosts.generated.conf"
    mapping: dict[str, str] = {}
    if hosts.exists():
        for line in hosts.read_text(encoding="utf-8").splitlines():
            m = re.match(r"host-record=([^,]+),([0-9.]+)", line.strip())
            if m:
                mapping[m.group(1)] = m.group(2)
    out = raw.replace("endpoint: alloy:4317", "endpoint: 127.0.0.1:4317")
    for name, ip in mapping.items():
        out = out.replace(f"{name}:57400:", f"{ip}:57400:")
    return out


def ktranslate_state_mount() -> str:
    return """            - name: device-state
              mountPath: /state
              readOnly: true"""


def load_group_listener_ports() -> dict[str, tuple[int, int]]:
    ports: dict[str, tuple[int, int]] = {}
    for env in sorted((LOCAL / "groups").glob("*.env")):
        group = metal = trap = None
        for line in env.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("GROUP="):
                group = line.split("=", 1)[1].strip()
            elif line.startswith("METALISTEN_PORT="):
                metal = int(line.split("=", 1)[1].strip())
            elif line.startswith("TRAP_PORT="):
                trap = int(line.split("=", 1)[1].strip())
        if group and metal is not None and trap is not None:
            ports[group] = (metal, trap)
    return ports


def snmp_deployments(
    groups: list[tuple[str, str]], host: str, listener_ports: dict[str, tuple[int, int]]
) -> str:
    docs: list[str] = []
    for group, _ in groups:
        name = f"ktranslate-snmp-{group}"
        svc = f"snmp-{group}"
        metal, trap = listener_ports.get(group, (9997, 1620))
        docs.append(
            f"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {NAMESPACE}
  labels:
    app: {name}
    component: ktranslate-golden
spec:
  replicas: 1
{HOST_NETWORK_STRATEGY}  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: ktranslate
          image: {KTRANSLATE_IMAGE}
{ktranslate_env(name, host)}
          args:
            - --format=otel
            - --format_metric=otel
            - --otel.protocol=grpc
            - --otel.endpoint=http://127.0.0.1:4317/
            - --snmp=/etc/ktranslate/poller.yaml
            - --metalisten=0.0.0.0:{metal}
            - --sinks=otel
            - --metrics=jchf
            - --tee_logs=true
            - --service_name={svc}
            - --max_flows_per_message=100
          ports:
            - name: traps
              containerPort: {trap}
              protocol: UDP
            - name: meta
              containerPort: {metal}
              protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_RAW"]
          volumeMounts:
            - name: poller-config
              mountPath: /etc/ktranslate/poller.yaml
              subPath: poller.yaml
              readOnly: true
            - name: snmp-profile
              mountPath: /etc/ktranslate/profiles/kentik_snmp/nokia/nokia-srlinux.yml
              subPath: nokia-srlinux.yml
              readOnly: true
{ktranslate_state_mount()}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: poller-config
          configMap:
            name: ktranslate-poller-{group}
        - name: snmp-profile
          configMap:
            name: snmp-profiles
        - name: device-state
          hostPath:
            path: {STATE_HOST_PATH}
            type: DirectoryOrCreate
"""
        )
    return "\n---\n".join(docs)


def flow_collector(
    name: str,
    svc: str,
    host: str,
    nf_port: int | None,
    nf_source: str | None,
    meta_port: int,
    extra_args: list[str],
) -> str:
    args = [
        "--format=otel",
        "--format_metric=otel",
        "--otel.protocol=grpc",
        "--otel.endpoint=http://127.0.0.1:4317/",
        "--snmp=/etc/ktranslate/catalog.yaml",
        "--flow_only=true",
        f"--metalisten=0.0.0.0:{meta_port}",
        "--sinks=otel",
        "--metrics=jchf",
        "--tee_logs=true",
        f"--service_name={svc}",
        "--max_flows_per_message=100",
    ]
    if nf_port is not None and nf_source is not None:
        args.extend(
            [
                f"--nf.source={nf_source}",
                f"--nf.port={nf_port}",
                "--rollup_interval=60",
                "--rollup_top_k=100",
                "--rollups=s_sum,bytes_by_flow,in_bytes+out_bytes,src_addr,dst_addr,l4_src_port,l4_dst_port,protocol,custom_str.application,device_name,custom_str.src_host,custom_str.dst_host,src_geo,dst_geo",
                "--rollup_keep_undefined=true",
            ]
        )
    args.extend(extra_args)
    arg_lines = "\n".join(f"            - {a}" for a in args)
    ports = [f"            - name: meta\n              containerPort: {meta_port}\n              protocol: TCP"]
    if nf_port is not None:
        ports.insert(
            0,
            f"            - name: nf\n              containerPort: {nf_port}\n              protocol: UDP",
        )
    port_block = "\n".join(ports)
    return f"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {NAMESPACE}
  labels:
    app: {name}
    component: ktranslate-golden
spec:
  replicas: 1
{HOST_NETWORK_STRATEGY}  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: ktranslate
          image: {KTRANSLATE_IMAGE}
{ktranslate_env(name, host)}
          args:
{arg_lines}
          ports:
{port_block}
          volumeMounts:
            - name: catalog
              mountPath: /etc/ktranslate/catalog.yaml
              subPath: catalog.yaml
              readOnly: true
{ktranslate_state_mount()}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: catalog
          configMap:
            name: ktranslate-device-catalog
        - name: device-state
          hostPath:
            path: {STATE_HOST_PATH}
            type: DirectoryOrCreate
"""


def poller_configmaps(groups: list[tuple[str, str]]) -> str:
    parts = []
    for group, yaml in groups:
        parts.append(
            f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: ktranslate-poller-{group}
  namespace: {NAMESPACE}
data:
  poller.yaml: |
{yaml_block(yaml)}
"""
        )
    return "\n---\n".join(parts)


def k8s_dnsmasq_conf(text: str) -> str:
    """dnsmasq.conf for hostNetwork k3s: no eth0 bind (listen via deployment args)."""
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped in ("bind-interfaces", "interface=eth0", "port=53"):
            continue
        lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def flow_dns_manifest(host: str) -> str:
    dnsmasq = LOCAL / "dnsmasq"
    files = {
        "dnsmasq.conf": k8s_dnsmasq_conf(read_text(dnsmasq / "dnsmasq.conf")),
        "hosts.generated.conf": read_text(dnsmasq / "hosts.generated.conf"),
        "upstream.conf": read_text(dnsmasq / "upstream.conf"),
        "extra-hosts.conf": read_text(dnsmasq / "extra-hosts.conf"),
    }
    cm_data = ""
    for fname, content in files.items():
        cm_data += f"  {fname}: |\n{yaml_block(content)}\n"
    return f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-dns-config
  namespace: {NAMESPACE}
data:
{cm_data}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-dns
  namespace: {NAMESPACE}
  labels:
    app: flow-dns
    component: ktranslate-golden
spec:
  replicas: 1
{HOST_NETWORK_STRATEGY}  selector:
    matchLabels:
      app: flow-dns
  template:
    metadata:
      labels:
        app: flow-dns
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: dnsmasq
          image: andyshinn/dnsmasq:2.83
          args:
            - --keep-in-foreground
            - --listen-address=127.0.0.1
            - --conf-file=/etc/dnsmasq.conf
            - --conf-dir=/etc/dnsmasq.d
          volumeMounts:
            - name: config
              mountPath: /etc/dnsmasq.conf
              subPath: dnsmasq.conf
            - name: config
              mountPath: /etc/dnsmasq.d/hosts.generated.conf
              subPath: hosts.generated.conf
            - name: config
              mountPath: /etc/dnsmasq.d/upstream.conf
              subPath: upstream.conf
            - name: config
              mountPath: /etc/dnsmasq.d/extra-hosts.conf
              subPath: extra-hosts.conf
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: flow-dns-config
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    run_generate_groups()
    host = load_ktrans_host()
    groups = load_poller_configs()
    listener_ports = load_group_listener_ports()
    catalog_path = LOCAL / "config" / "catalog.yaml"
    if not catalog_path.exists():
        raise SystemExit(f"missing {catalog_path}")

    for tmpl in sorted(TEMPLATES.glob("*.yaml.tmpl")):
        body = read_text(tmpl).replace("__KTRANS_HOST__", host)
        write_manifest(tmpl.name.replace(".yaml.tmpl", ".yaml"), body, args.dry_run)

    write_manifest(
        "lab-host-identity.yaml",
        f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-host-identity
  namespace: {NAMESPACE}
data:
  KTRANS_HOST: "{host}"
""",
        args.dry_run,
    )

    alloy_cfg = read_text(LOCAL / "alloy" / "config.alloy")
    write_manifest(
        "alloy-configmap.yaml",
        f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {NAMESPACE}
data:
  config.alloy: |
{yaml_block(alloy_cfg)}
""",
        args.dry_run,
    )

    profile = read_text(LOCAL / "snmp-profiles" / "nokia" / "nokia-srlinux.yml")
    write_manifest(
        "snmp-profiles-configmap.yaml",
        f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-profiles
  namespace: {NAMESPACE}
data:
  nokia-srlinux.yml: |
{yaml_block(profile)}
""",
        args.dry_run,
    )

    catalog = read_text(catalog_path)
    write_manifest(
        "catalog-configmap.yaml",
        f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: ktranslate-device-catalog
  namespace: {NAMESPACE}
data:
  catalog.yaml: |
{yaml_block(catalog)}
""",
        args.dry_run,
    )

    gnmic_path = LOCAL / "gnmic" / "gnmic.yaml"
    env_file = LOCAL / ".env"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if line.startswith("LAB_FABRIC_PROFILE="):
                profile = line.split("=", 1)[1].strip().lower()
                if profile in {"colocated", "hq-branches", "aws"}:
                    gnmic_path = LOCAL / "gnmic" / "gnmic-colocated.yaml"
                break
    gnmic = patch_gnmic_config(read_text(gnmic_path))
    write_manifest(
        "gnmic-configmap.yaml",
        f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: gnmic-config
  namespace: {NAMESPACE}
data:
  gnmic.yaml: |
{yaml_block(gnmic)}
""",
        args.dry_run,
    )

    write_manifest("ktranslate-poller-configmaps.yaml", poller_configmaps(groups), args.dry_run)
    write_manifest("ktranslate-snmp.yaml", snmp_deployments(groups, host, listener_ports), args.dry_run)
    write_manifest(
        "ktranslate-flow.yaml",
        flow_collector("ktranslate-flow", "flow", host, 9995, "netflow9", 9996, ["--dns=127.0.0.1:53"]),
        args.dry_run,
    )
    write_manifest(
        "ktranslate-sflow.yaml",
        flow_collector("ktranslate-sflow", "flow-sflow", host, 6343, "sflow", 9994, ["--dns=127.0.0.1:53"]),
        args.dry_run,
    )
    write_manifest(
        "ktranslate-syslog.yaml",
        flow_collector(
            "ktranslate-syslog",
            "syslog",
            host,
            None,
            None,
            9998,
            ["--syslog.source=0.0.0.0:1514"],
        ),
        args.dry_run,
    )
    write_manifest("flow-dns.yaml", flow_dns_manifest(host), args.dry_run)

    resources = [
        "namespace.yaml",
        "lab-host-identity.yaml",
        "alloy-configmap.yaml",
        "alloy.yaml",
        "flow-dns.yaml",
        "snmp-profiles-configmap.yaml",
        "catalog-configmap.yaml",
        "ktranslate-poller-configmaps.yaml",
        "ktranslate-snmp.yaml",
        "ktranslate-flow.yaml",
        "ktranslate-sflow.yaml",
        "ktranslate-syslog.yaml",
        "gnmic-configmap.yaml",
        "gnmic.yaml",
    ]
    kust = "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n"
    kust += "\n".join(f"  - {r}" for r in resources)
    write_manifest("kustomization.yaml", kust, args.dry_run)

    if not args.dry_run:
        print(f"done — apply with: bash local/scripts/deploy-ktranslate-golden.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
