#!/usr/bin/env python3
"""Render local/orb/agent.generated.yaml from env + defaults."""
from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ORB = ROOT / "orb"
OUT = ORB / "agent.generated.yaml"


def env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip() or default


def main() -> None:
    dry = env("ORB_DRY_RUN", "1") not in ("0", "false", "False", "no")
    targets = env("ORB_SNMP_TARGETS", "172.20.20.0/24")
    community = env("ORB_SNMP_COMMUNITY", "public")
    pkt = env("ORB_PKTVISOR", "0") in ("1", "true", "True", "yes")
    otlp_on = pkt or env("ORB_OTLP", "0") in ("1", "true", "True", "yes")
    diode_target = env("ORB_DIODE_TARGET", "grpc://127.0.0.1:8080/diode")
    agent_name = env("ORB_AGENT_NAME", "network-o11y-lab")
    schedule = env("ORB_SNMP_SCHEDULE", "*/2 * * * *")
    otlp_grpc = env("ORB_OTLP_GRPC", "grpc://127.0.0.1:4317")
    otlp_http = env("ORB_OTLP_HTTP", "http://127.0.0.1:4318")

    target_hosts = [t.strip() for t in targets.replace(";", ",").split(",") if t.strip()]
    targets_yaml = "\n".join(f'            - host: "{h}"' for h in target_hosts)

    if dry:
        diode_block = f"""      diode:
        dry_run: true
        dry_run_output_dir: /opt/orb/out
        agent_name: {agent_name}"""
    else:
        # Resolve secrets at render time — orb-agent does not always expand
        # ${DIODE_CLIENT_*} placeholders for diode client fields.
        cid = env("DIODE_CLIENT_ID", "")
        csec = env("DIODE_CLIENT_SECRET", "")
        if not cid or not csec:
            raise SystemExit(
                "ORB_DRY_RUN=0 requires DIODE_CLIENT_ID and DIODE_CLIENT_SECRET in the environment"
            )
        diode_block = f"""      diode:
        target: "{diode_target}"
        client_id: "{cid}"
        client_secret: "{csec}"
        agent_name: {agent_name}"""

    pktvisor_backend = ""
    pktvisor_policies = ""
    if pkt:
        pktvisor_backend = f"""
    pktvisor:
      host: 0.0.0.0
      port: "10853"
      taps:
        lab_netflow:
          input_type: flow
          config:
            flow_type: netflow
            port: {env("ORB_PKTVISOR_NETFLOW_PORT", "19995")}
            bind: 0.0.0.0
        lab_sflow:
          input_type: flow
          config:
            flow_type: sflow
            port: {env("ORB_PKTVISOR_SFLOW_PORT", "16343")}
            bind: 0.0.0.0
"""
        # Flow taps only support the flow handler (dns/dhcp/net need pcap).
        pktvisor_policies = """
    pktvisor:
      lab_netflow_summary:
        kind: collection
        input:
          input_type: flow
          tap: lab_netflow
        handlers:
          config:
            topn_count: 25
          modules:
            flow_overview:
              type: flow
              metric_groups:
                enable:
                  - cardinality
                  - counters
                  - by_packets
                  - by_bytes
                  - top_ips
                  - top_ports
                  - top_ips_ports
                  - conversations
      lab_sflow_summary:
        kind: collection
        input:
          input_type: flow
          tap: lab_sflow
        handlers:
          config:
            topn_count: 25
          modules:
            flow_overview:
              type: flow
              metric_groups:
                enable:
                  - cardinality
                  - counters
                  - by_packets
                  - by_bytes
                  - top_ips
                  - top_ports
                  - conversations
"""

    # common.otlp / otel only when Alloy is expected (pktvisor or ORB_OTLP=1)
    otlp_block = ""
    if otlp_on:
        otlp_block = f"""
      otlp:
        grpc: "{otlp_grpc}"
        http: "{otlp_http}"
        agent_labels:
          deployment_host: orb-agent
          collector: orb
      otel:
        grpc: "{otlp_grpc}"
        agent_labels:
          deployment_host: orb-agent
          collector: orb"""

    text = f"""# Generated by scripts/orb-render-config.py — do not edit; make orb-up regenerates.
orb:
  config_manager:
    active: local
  labels:
    lab: network-o11y-demo
    role: orb-sidecar
  backends:
    snmp_discovery:
      ingest_buffer_size: 128
{pktvisor_backend}
    common:
{diode_block}{otlp_block}
  policies:
    snmp_discovery:
      lab_clos_snmp:
        config:
          schedule: "{schedule}"
          timeout: 180
          snmp_timeout: 5
          retries: 1
          defaults:
            tags: ["orb", "snmp-discovery", "network-o11y-lab"]
            site: "Network Lab"
            role: "network"
            device:
              description: "Discovered by Orb snmp_discovery (lab sidecar)"
            interface:
              if_type: "other"
        scope:
          targets:
{targets_yaml}
          authentication:
            protocol_version: "SNMPv2c"
            community: "${{SNMP_COMMUNITY}}"
{pktvisor_policies}
"""
    ORB.mkdir(parents=True, exist_ok=True)
    (ORB / "out").mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    mode = "dry_run" if dry else "diode"
    pkt_s = "pktvisor=on" if pkt else "pktvisor=off"
    otlp_s = "otlp=on" if otlp_on else "otlp=off"
    print(f"wrote {OUT} ({mode}, targets={target_hosts}, {pkt_s}, {otlp_s})")


if __name__ == "__main__":
    main()
