#!/usr/bin/env bash
# refresh-flow-dns.sh — regenerate dnsmasq host-records for ktranslate flow DNS.
#
# ktranslate --dns needs reverse PTR for flow IPs → custom_str.src_host / dst_host.
# Records are built from:
#   1. state/devices-*.yaml (SNMP discovery: device_name + device_ip)
#   2. dnsmasq/extra-hosts.conf (operator-edited; optional)
#   3. FLOW_DNS_EXTRA_HOSTS in .env (name:ip,name2:ip2)
#   4. FLOW_DNS_DOCKER_NETWORK + FLOW_DNS_DOCKER_NODES (optional lab overlay)
#
# Upstream recursion: FLOW_DNS_UPSTREAM (default host.docker.internal).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DNSMASQ_DIR="${REPO_ROOT}/dnsmasq"
HOSTS_OUT="${DNSMASQ_DIR}/hosts.generated.conf"
UPSTREAM_OUT="${DNSMASQ_DIR}/upstream.conf"
FLOW_DNS_SERVICE="${FLOW_DNS_SERVICE:-flow_dns}"

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

# Load .env when present (FLOW_DNS_* knobs).
if [[ -f "${REPO_ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${REPO_ROOT}/.env"
  set +a
fi

UPSTREAM="${FLOW_DNS_UPSTREAM:-host.docker.internal}"

# dnsmasq requires a literal IP in server= (hostnames fail at parse time).
resolve_upstream_ip() {
  local target="$1"
  if [[ "$target" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "$target"
    return
  fi
  local ip=""
  ip="$(getent hosts "$target" 2>/dev/null | awk '{print $1}' | head -1 || true)"
  if [[ -z "$ip" ]]; then
    ip="$(docker run --rm --add-host=host.docker.internal:host-gateway alpine getent hosts "$target" 2>/dev/null | awk '{print $1}' | head -1 || true)"
  fi
  if [[ -z "$ip" ]]; then
    die "cannot resolve FLOW_DNS_UPSTREAM=${target} — set FLOW_DNS_UPSTREAM to an IP"
  fi
  echo "$ip"
}
UPSTREAM_IP="$(resolve_upstream_ip "$UPSTREAM")"

command -v python3 >/dev/null || die "python3 required"
command -v yq >/dev/null || die "yq required — https://github.com/mikefarah/yq"

mkdir -p "${DNSMASQ_DIR}"

{
  echo "# Generated by scripts/refresh-flow-dns.sh — do not edit by hand."
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  python3 - "${REPO_ROOT}" <<'PY'
import os
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
state = root / "state"
seen: set[tuple[str, str]] = set()
lines: list[str] = []

def add(name: str, ip: str, source: str) -> None:
    name = (name or "").strip()
    ip = (ip or "").strip()
    if not name or not ip:
        return
    if not re.match(r"^[\w.-]+$", name):
        return
    key = (name, ip)
    if key in seen:
        return
    seen.add(key)
    lines.append(f"host-record={name},{ip}  # {source}")

for path in sorted(state.glob("devices-*.yaml")):
    try:
        import yaml
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception as exc:
        print(f"# skip {path.name}: {exc}", file=sys.stderr)
        continue
    devs = data.get("devices", data) if isinstance(data, dict) else {}
    if not isinstance(devs, dict):
        continue
    for key, cfg in devs.items():
        if not isinstance(cfg, dict):
            continue
        ip = cfg.get("device_ip") or cfg.get("ip")
        name = cfg.get("device_name") or key
        add(str(name), str(ip), f"devices/{path.name}")

extra_hosts = root / "dnsmasq" / "extra-hosts.conf"
if extra_hosts.is_file():
    for raw in extra_hosts.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("host-record="):
            lines.append(line + "  # extra-hosts.conf")
        elif "," in line:
            name, ip = line.split(",", 1)
            add(name, ip, "extra-hosts.conf")

extra_env = os.environ.get("FLOW_DNS_EXTRA_HOSTS", "")
for pair in extra_env.split(","):
    pair = pair.strip()
    if not pair or ":" not in pair:
        continue
    name, ip = pair.split(":", 1)
    add(name, ip, "FLOW_DNS_EXTRA_HOSTS")

docker_net = os.environ.get("FLOW_DNS_DOCKER_NETWORK", "").strip()
docker_nodes = os.environ.get("FLOW_DNS_DOCKER_NODES", "").strip()
if docker_net and docker_nodes:
    import subprocess

    for node in docker_nodes.split():
        try:
            out = subprocess.check_output(
                [
                    "docker", "inspect",
                    "-f", f"{{{{(index .NetworkSettings.Networks \"{docker_net}\").IPAddress}}}}",
                    node,
                ],
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
        except subprocess.CalledProcessError:
            continue
        if out and out != "<no value>":
            add(node, out, f"docker/{docker_net}")

print("\n".join(lines))
PY
} > "${HOSTS_OUT}"

{
  echo "# Generated by scripts/refresh-flow-dns.sh — do not edit by hand."
  echo "server=${UPSTREAM_IP}"
} > "${UPSTREAM_OUT}"

info "Wrote ${HOSTS_OUT} ($(grep -c '^host-record=' "${HOSTS_OUT}" 2>/dev/null || echo 0) records)"
info "Wrote ${UPSTREAM_OUT} (upstream=${UPSTREAM} -> ${UPSTREAM_IP})"

if docker inspect "${FLOW_DNS_SERVICE}" >/dev/null 2>&1; then
  info "Reloading ${FLOW_DNS_SERVICE}..."
  docker restart "${FLOW_DNS_SERVICE}" >/dev/null
  info "${FLOW_DNS_SERVICE} reloaded"
else
  info "${FLOW_DNS_SERVICE} not running — start stack with: make up"
fi

info "Verify: docker exec ktranslate_flow nslookup <device-ip> ${FLOW_DNS_SERVICE}"
