#!/usr/bin/env bash
# Render alloy/snmp-trap.generated.alloy
#
# LAB_ALLOY_SNMPTRAP=1 — loki.source.snmptrap on :1620
# LAB_ALLOY_SYSLOG=1   — loki.source.syslog on :1514
# Both join device_name from /etc/alloy/snmp-targets.yml (file-SD catalog).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/alloy/snmp-trap.generated.alloy"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "${ROOT}/.env" | awk -F= '
    /^[[:space:]]*#/ || NF<2 { next }
    {
      key=$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key != "" && !(key in ENVIRON && ENVIRON[key] != "")) print
    }
  ')
  set +a
fi

mkdir -p "${ROOT}/alloy" "${ROOT}/fixtures/alloy-snmp/mibs"
bash "${ROOT}/scripts/stage-alloy-mibs.sh" || true

enabled_trap=0
case "${LAB_ALLOY_SNMPTRAP:-0}" in
  1|true|TRUE|yes|YES|on|ON) enabled_trap=1 ;;
esac
enabled_syslog=0
case "${LAB_ALLOY_SYSLOG:-0}" in
  1|true|TRUE|yes|YES|on|ON) enabled_syslog=1 ;;
esac

{
  echo "// GENERATED by scripts/render-alloy-snmp-trap.sh — do not edit by hand."
  echo "// Re-run: make generate  (or bash scripts/render-alloy-snmp-trap.sh)"
  echo ""
  if [[ "${enabled_trap}" != "1" && "${enabled_syslog}" != "1" ]]; then
    echo "// LAB_ALLOY_SNMPTRAP=0 LAB_ALLOY_SYSLOG=0 — Alloy trap/syslog receivers disabled."
  else
    cat <<'EOF'
// Device catalog for trap/syslog join (same YAML as Alloy SNMP scrape).
local.file "device_join_catalog" {
  filename       = "/etc/alloy/snmp-targets.yml"
  detector       = "poll"
  poll_frequency = "15s"
}

EOF
    if [[ "${enabled_trap}" == "1" ]]; then
      cat <<'EOF'
// LAB_ALLOY_SNMPTRAP=1 — SNMP traps/informs as Loki logs (experimental).
// Query: {service_name="alloy-snmptrap"} | json

loki.relabel "snmptrap" {
  forward_to = []

  rule {
    source_labels = ["__snmptrap_name"]
    target_label  = "trap"
  }

  rule {
    source_labels = ["__snmptrap_oid"]
    target_label  = "trap_oid"
  }

  rule {
    source_labels = ["__snmptrap_source"]
    target_label  = "source"
  }

  rule {
    source_labels = ["__snmptrap_version"]
    target_label  = "snmp_version"
  }

  rule {
    source_labels = ["__snmptrap_pdu"]
    target_label  = "pdu_type"
  }
}

loki.source.snmptrap "lab" {
  listen_address = "0.0.0.0:1620"
  mib_paths      = ["/etc/alloy/mibs"]
  targets        = encoding.from_yaml(local.file.device_join_catalog.content)
  labels         = {
    job       = "snmptrap",
    collector = "alloy-snmptrap",
  }
  relabel_rules  = loki.relabel.snmptrap.rules
  forward_to     = [otelcol.receiver.loki.snmptrap.receiver]
}

otelcol.receiver.loki "snmptrap" {
  output {
    logs = [otelcol.processor.transform.snmptrap_logs.input]
  }
}

otelcol.processor.transform "snmptrap_logs" {
  error_mode = "ignore"

  log_statements {
    context = "resource"
    statements = [
      `set(attributes["collector"], "alloy-snmptrap")`,
      `set(attributes["service.name"], "alloy-snmptrap")`,
    ]
  }

  output {
    logs = [otelcol.processor.resourcedetection.default.input]
  }
}

EOF
    fi
    if [[ "${enabled_syslog}" == "1" ]]; then
      cat <<'EOF'
// LAB_ALLOY_SYSLOG=1 — device syslog as Loki logs.
// Query: {service_name="alloy-syslog"}
// SR Linux remote syslog is RFC5424-shaped on this lab.

loki.relabel "syslog" {
  forward_to = []

  rule {
    source_labels = ["__syslog_message_severity"]
    target_label  = "severity"
  }

  rule {
    source_labels = ["__syslog_message_facility"]
    target_label  = "facility"
  }

  rule {
    source_labels = ["__syslog_message_hostname"]
    target_label  = "hostname"
  }

  rule {
    source_labels = ["__syslog_connection_ip_address"]
    target_label  = "source"
  }
}

loki.source.syslog "lab" {
  targets       = encoding.from_yaml(local.file.device_join_catalog.content)
  relabel_rules = loki.relabel.syslog.rules
  forward_to    = [otelcol.receiver.loki.syslog.receiver]

  listener {
    address       = "0.0.0.0:1514"
    protocol      = "udp"
    syslog_format = "rfc5424"
    labels        = {
      job       = "syslog",
      collector = "alloy-syslog",
    }
  }
}

otelcol.receiver.loki "syslog" {
  output {
    logs = [otelcol.processor.transform.syslog_logs.input]
  }
}

otelcol.processor.transform "syslog_logs" {
  error_mode = "ignore"

  log_statements {
    context = "resource"
    statements = [
      `set(attributes["collector"], "alloy-syslog")`,
      `set(attributes["service.name"], "alloy-syslog")`,
    ]
  }

  output {
    logs = [otelcol.processor.resourcedetection.default.input]
  }
}

EOF
    fi
  fi
} > "${OUT}"

echo "==> wrote ${OUT} (LAB_ALLOY_SNMPTRAP=${LAB_ALLOY_SNMPTRAP:-0} LAB_ALLOY_SYSLOG=${LAB_ALLOY_SYSLOG:-0})"
