#!/usr/bin/env bash
# Render alloy/remotecfg.generated.alloy for Grafana Fleet Management enrollment.
#
# LAB_ALLOY_FLEET=0 (default): comment-only file so Alloy still loads it.
# LAB_ALLOY_FLEET=1: remotecfg block polls Fleet; requires GC_FM_URL + GC_FM_TOKEN.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/alloy/remotecfg.generated.alloy"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  # Do not clobber vars already exported by the caller (e.g. LAB_ALLOY_FLEET=0).
  source <(sed 's/\r$//' "${ROOT}/.env" | awk -F= '
    /^[[:space:]]*#/ || NF<2 { next }
    {
      key=$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key != "" && !(key in ENVIRON && ENVIRON[key] != "")) print
    }
  ')
  set +a
fi

mkdir -p "${ROOT}/alloy"

enabled=0
case "${LAB_ALLOY_FLEET:-0}" in
  1|true|yes|on|TRUE|YES|ON) enabled=1 ;;
esac

FM_URL="${GC_FM_URL:-}"
FM_USER="${GC_FM_USER:-${GC_OTLP_ACCOUNT:-}}"
FM_ID="${GC_FM_COLLECTOR_ID:-network-o11y-lab-${KTRANS_HOST:-alloy}}"
POLL="${GC_FM_POLL_FREQUENCY:-1m}"

{
  echo "// GENERATED by scripts/render-alloy-remotecfg.sh — do not edit by hand."
  if [[ "${enabled}" -eq 0 ]]; then
    echo "// LAB_ALLOY_FLEET=0 — remotecfg disabled (local River only)."
  else
    if [[ -z "${FM_URL}" || -z "${FM_USER}" ]]; then
      echo "ERROR: LAB_ALLOY_FLEET=1 requires GC_FM_URL and GC_FM_USER (or GC_OTLP_ACCOUNT)" >&2
      exit 1
    fi
    # password from env so the token never lands in the River file on disk.
    cat <<EOF
// LAB_ALLOY_FLEET=1 — enroll this Alloy in Grafana Fleet Management.
// SNMP scrape may still be local (LAB_ALLOY_SNMP) or Fleet-owned (LAB_ALLOY_FLEET_SNMP=1).
// API URL: Connections → Collector → Fleet Management → API tab.

remotecfg {
  url = "${FM_URL}"

  basic_auth {
    username = "${FM_USER}"
    password = env("GC_FM_TOKEN")
  }

  id             = "${FM_ID}"
  name           = "${FM_ID}"
  poll_frequency = "${POLL}"

  attributes = {
    "lab"       = "network-o11y-demo",
    "role"      = "network-snmp",
    "collector" = "alloy-fleet-lab",
    "host"      = env("KTRANS_HOST"),
  }
}
EOF
  fi
} > "${OUT}"

echo "==> wrote ${OUT} (LAB_ALLOY_FLEET=${LAB_ALLOY_FLEET:-0} id=${FM_ID})"
