#!/usr/bin/env bash
# Render Alloy OTLP export block (1–3 Grafana Cloud sinks).
# Extra sinks when GC_OTLP_*_2 and/or GC_OTLP_*_3 are fully set in local/.env.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/alloy/otlp-export.generated.alloy"
ENV_FILE="${REPO_ROOT}/.env"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "$ENV_FILE")
  set +a
fi

have_pair() {
  local n="$1"
  local u a k
  eval "u=\${GC_OTLP_URL_${n}:-}"
  eval "a=\${GC_OTLP_ACCOUNT_${n}:-}"
  eval "k=\${GC_OTLP_KEY_${n}:-}"
  [[ -n "$u" && -n "$a" && -n "$k" ]]
}

extra=()
if have_pair 2; then
  extra+=(2)
fi
if have_pair 3; then
  extra+=(3)
fi

sinks=$((1 + ${#extra[@]}))

{
  echo "// GENERATED by scripts/render-alloy-otlp-export.sh — do not edit by hand."
  echo "// Re-run: make generate  (or bash scripts/render-alloy-otlp-export.sh)"
  echo "// OTLP sinks: ${sinks} (set GC_OTLP_*_2 / GC_OTLP_*_3 in .env to fan-out)."
  echo ""
  echo 'otelcol.processor.batch "default" {'
  echo '  output {'

  refs="otelcol.exporter.otlphttp.grafana_cloud.input"
  for n in "${extra[@]}"; do
    refs+=", otelcol.exporter.otlphttp.grafana_cloud_${n}.input"
  done
  echo "    metrics = [${refs}]"
  echo "    logs    = [${refs}]"
  echo "    traces  = [${refs}]"
  echo '  }'
  echo '}'
  echo ""
  cat <<'EOF'
otelcol.exporter.otlphttp "grafana_cloud" {
  client {
    endpoint = env("GC_OTLP_URL")
    auth     = otelcol.auth.basic.grafana_cloud.handler
  }
}

otelcol.auth.basic "grafana_cloud" {
  username = env("GC_OTLP_ACCOUNT")
  password = env("GC_OTLP_KEY")
}
EOF

  for n in "${extra[@]}"; do
    cat <<EOF

otelcol.exporter.otlphttp "grafana_cloud_${n}" {
  client {
    endpoint = env("GC_OTLP_URL_${n}")
    auth     = otelcol.auth.basic.grafana_cloud_${n}.handler
  }
}

otelcol.auth.basic "grafana_cloud_${n}" {
  username = env("GC_OTLP_ACCOUNT_${n}")
  password = env("GC_OTLP_KEY_${n}")
}
EOF
  done
} >"${OUT}"

echo "wrote ${OUT} (sinks=${sinks})"
