#!/usr/bin/env bash
# Pin Alloy SNMP topology modules on live SRL mgmt IPs.
#
# Nokia fingerprinters still emit modules_topology: [] so enabling the
# topology scrape tier alone walks nothing. discovery.snmp overrides
# set module_topology without touching hot/cold.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=fabric-nodes.sh
source "${ROOT}/scripts/fabric-nodes.sh"
fabric_profile_init

OUT="${ROOT}/alloy/snmp-overrides.yml"
CLAB_NET="${CLAB_NETWORK:-clab}"
# TIMOS BGP table + IEEE LLDP-MIB. SRL may answer one, both, or neither.
TOPO_MODULES="${ALLOY_SNMP_TOPOLOGY_MODULES:-nokia_srlinux_topo,lldp_mib}"

mkdir -p "${ROOT}/alloy"

node_ip() {
  docker inspect -f "{{(index .NetworkSettings.Networks \"${CLAB_NET}\").IPAddress}}" "$1" 2>/dev/null || true
}

{
  echo "# GENERATED by scripts/render-snmp-topology-overrides.sh — topology module pins."
  echo "# Hot/cold stay on the fingerprinter. Do not put communities here."
  echo "overrides:"
  for n in "${SRL_NODES[@]}"; do
    ip="$(node_ip "$n")"
    [[ -n "${ip}" && "${ip}" != "<no value>" ]] || continue
    echo "- address: ${ip}"
    echo "  name: ${n}"
    echo "  module_topology: ${TOPO_MODULES}"
  done
} > "${OUT}"

n="$(grep -c '^  name:' "${OUT}" || true)"
echo "==> wrote ${OUT} (${n} topology pin(s), modules=${TOPO_MODULES})"
