#!/usr/bin/env bash
# Render alloy/netflow.generated.alloy
#
# LAB_ALLOY_NETFLOW=1         — otelcol.receiver.netflow (NetFlow/IPFIX + optional sFlow)
# LAB_ALLOY_NETFLOW_METRICS=1 — default ON when netflow is on: signaltometrics sums
# LAB_ALLOY_NETFLOW_LOGS=1    — default OFF: punt decoded records to the existing OTLP logs path
# LAB_ALLOY_NETFLOW_SFLOW=1   — default ON when netflow is on: second listener (sFlow)
#
# Does not steal ktranslate ports (9995 / 6343). Alloy listens on 2055 (IPFIX) and 6344 (sFlow).
# Host maps: 12055/udp → 2055, 16344/udp → 6344. Point a second exporter at the Alloy clab IP.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/alloy/netflow.generated.alloy"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "${ROOT}/.env" | awk -F= '
    /^[[:space:]]*#/ || NF<2 { next }
    {
      key=$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key != "" && !(key in ENVIRON && ENVIRON[key] != "")) print
    }
  ')
  set +a
fi

flag_on() {
  case "${1:-0}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

flag_off() {
  case "${1:-}" in
    0|false|FALSE|no|NO|off|OFF) return 0 ;;
    *) return 1 ;;
  esac
}

enabled=0
flag_on "${LAB_ALLOY_NETFLOW:-0}" && enabled=1

logs=0
flag_on "${LAB_ALLOY_NETFLOW_LOGS:-0}" && logs=1

metrics=0
sflow=0
if [[ "${enabled}" == "1" ]]; then
  if flag_off "${LAB_ALLOY_NETFLOW_METRICS:-1}"; then
    metrics=0
  else
    metrics=1
  fi
  if flag_off "${LAB_ALLOY_NETFLOW_SFLOW:-1}"; then
    sflow=0
  else
    sflow=1
  fi
  if [[ "${metrics}" != "1" && "${logs}" != "1" ]]; then
    echo "NOTE: LAB_ALLOY_NETFLOW=1 with metrics and logs both off — enabling metrics." >&2
    metrics=1
  fi
fi

NF_PORT="${LAB_ALLOY_NETFLOW_PORT:-2055}"
SF_PORT="${LAB_ALLOY_SFLOW_PORT:-6344}"

{
  echo "// GENERATED by scripts/render-alloy-netflow.sh — do not edit by hand."
  echo "// Re-run: make generate  (or bash scripts/render-alloy-netflow.sh)"
  echo ""
  if [[ "${enabled}" != "1" ]]; then
    echo "// LAB_ALLOY_NETFLOW=0 — Alloy-native flow receiver disabled."
    echo "// ktranslate_flow :9995 / ktranslate_sflow :6343 stay the lab default."
  else
    cat <<EOF
// LAB_ALLOY_NETFLOW=1 — contrib netflow receiver (logs pdata) + devicejoin.
// Metrics: signaltometrics (delta Sum) → deltatocumulative → Grafana Cloud.
//   Names are alloy.network.io.by_flow* — ktranslate already owns
//   network.io.by_flow as a gauge on this tenant; same name + Sum = OTLP 400.
//   PromQL: rate(alloy_network_io_by_flow_bytes{integration="alloy-netflow"}[5m])*8
// Logs: optional experimental punt onto the existing OTLP logs export.
// Do not point softflowd here unless you intend a dual-feed (Alpine: one -n per process).
// targets: same snmp-targets.yml catalog as traps/syslog (device_name / snmp_aliases).

local.file "netflow_device_join" {
  filename       = "/etc/alloy/snmp-targets.yml"
  detector       = "poll"
  poll_frequency = "15s"
}

otelcol.receiver.netflow "ipfix" {
  scheme   = "netflow"
  hostname = "0.0.0.0"
  port     = ${NF_PORT}
  targets  = encoding.from_yaml(local.file.netflow_device_join.content)

  output {
    logs = [otelcol.processor.transform.netflow_resource.input]
  }
}

EOF
    if [[ "${sflow}" == "1" ]]; then
      cat <<EOF
otelcol.receiver.netflow "sflow" {
  scheme   = "sflow"
  hostname = "0.0.0.0"
  port     = ${SF_PORT}
  targets  = encoding.from_yaml(local.file.netflow_device_join.content)

  output {
    logs = [otelcol.processor.transform.netflow_resource.input]
  }
}

EOF
    fi

    consumers=()
    if [[ "${metrics}" == "1" ]]; then
      consumers+=("otelcol.connector.signaltometrics.netflow.input")
    fi
    if [[ "${logs}" == "1" ]]; then
      consumers+=("otelcol.processor.resourcedetection.default.input")
    fi
    {
      echo "otelcol.processor.transform \"netflow_resource\" {"
      echo "  error_mode = \"ignore\""
      echo ""
      echo "  log_statements {"
      echo "    context = \"resource\""
      echo "    statements = ["
      echo "      \`set(resource.attributes[\"collector\"], \"alloy-netflow\")\`,"
      echo "      \`set(resource.attributes[\"service.name\"], \"alloy-netflow\")\`,"
      echo "    ]"
      echo "  }"
      echo ""
      echo "  output {"
      echo "    logs = ["
      for c in "${consumers[@]}"; do
        echo "      ${c},"
      done
      echo "    ]"
      echo "  }"
      echo "}"
      echo ""
    }

    if [[ "${metrics}" == "1" ]]; then
      cat <<'EOF'
otelcol.connector.signaltometrics "netflow" {
  error_mode = "ignore"

  logs {
    name        = "alloy.network.io.by_flow"
    description = "Bytes observed in decoded NetFlow/IPFIX/sFlow records"
    unit        = "By"
    include_resource_attributes {
      key = "service.name"
    }
    attributes {
      key = "source.address"
    }
    attributes {
      key = "source.port"
    }
    attributes {
      key = "destination.address"
    }
    attributes {
      key = "destination.port"
    }
    attributes {
      key = "network.transport"
    }
    attributes {
      key = "flow.sampler_address"
    }
    attributes {
      key = "device_name"
    }
    attributes {
      key = "src_device"
    }
    attributes {
      key = "dst_device"
    }
    attributes {
      key = "snmp_group"
    }
    sum {
      value = "Int(log.attributes[\"flow.io.bytes\"])"
    }
  }

  logs {
    name        = "alloy.network.io.by_flow.packets"
    description = "Packets observed in decoded NetFlow/IPFIX/sFlow records"
    unit        = "{packets}"
    include_resource_attributes {
      key = "service.name"
    }
    attributes {
      key = "source.address"
    }
    attributes {
      key = "source.port"
    }
    attributes {
      key = "destination.address"
    }
    attributes {
      key = "destination.port"
    }
    attributes {
      key = "network.transport"
    }
    attributes {
      key = "flow.sampler_address"
    }
    attributes {
      key = "device_name"
    }
    attributes {
      key = "src_device"
    }
    attributes {
      key = "dst_device"
    }
    attributes {
      key = "snmp_group"
    }
    sum {
      value = "Int(log.attributes[\"flow.io.packets\"])"
    }
  }

  output {
    metrics = [otelcol.processor.deltatocumulative.netflow.input]
  }
}

otelcol.processor.deltatocumulative "netflow" {
  max_stale   = "5m"
  max_streams = 100000

  output {
    metrics = [otelcol.processor.transform.netflow_metrics.input]
  }
}

otelcol.processor.transform "netflow_metrics" {
  error_mode = "ignore"

  metric_statements {
    context = "datapoint"
    statements = [
      `set(datapoint.attributes["integration"], "alloy-netflow")`,
    ]
  }

  output {
    metrics = [otelcol.processor.batch.default.input]
  }
}

EOF
    fi
  fi
} > "${OUT}"

echo "==> wrote ${OUT} (LAB_ALLOY_NETFLOW=${LAB_ALLOY_NETFLOW:-0} METRICS=${metrics} LOGS=${logs} SFLOW=${sflow})"
