#!/usr/bin/env bash
# Render alloy/snmp-scrape.generated.alloy and seed SNMP library / SD files.
#
# LAB_ALLOY_SNMP=0 (default): comment-only overlay so Alloy still loads the file.
# LAB_ALLOY_SNMP=1: discovery.file-style targets (encoding.from_yaml of snmp-targets.yml)
#   produced by snmp-discovery — named auth + sysObjectID→module, not static blocks.
# HTTP SD (snmp_discovery:9780/sd) is the poller-pool catalog; this file stays the
# laptop scrape path so a single Alloy does not need discovery.http.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/alloy/snmp-scrape.generated.alloy"
SNMP_YML="${ROOT}/alloy/snmp-network.yml"
FP_YML="${ROOT}/alloy/fingerprinters.yml"
TARGETS_YML="${ROOT}/alloy/snmp-targets.yml"
TARGETS_COLD_YML="${ROOT}/alloy/snmp-targets-cold.yml"
TARGETS_TOPO_YML="${ROOT}/alloy/snmp-targets-topology.yml"
# Compose bind-mounts targets at /etc/alloy. k3s hostPath-mounts local/alloy at /snmp-sd
# so the image-baked /etc/alloy/snmp-network.yml is not hidden.
SNMP_TARGETS_DIR="${ALLOY_SNMP_TARGETS_DIR:-/etc/alloy}"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  # Do not clobber vars already exported by the caller (e.g. LAB_ALLOY_FLEET_SNMP=0 fallback).
  source <(sed 's/\r$//' "${ROOT}/.env" | awk -F= '
    /^[[:space:]]*#/ || NF<2 { next }
    {
      key=$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key != "" && !(key in ENVIRON && ENVIRON[key] != "")) print
    }
  ')
  set +a
fi

mkdir -p "${ROOT}/alloy"

copy_from_lib() {
  local dest="$1" name="$2"
  local src=""
  if [[ -n "${ALLOY_SRC:-}" && -f "${ALLOY_SRC}/snmp/${name}" ]]; then
    src="${ALLOY_SRC}/snmp/${name}"
  elif [[ -f "${ROOT}/fixtures/alloy-snmp/${name}" ]]; then
    src="${ROOT}/fixtures/alloy-snmp/${name}"
  else
    local sibling
    sibling="$(cd "${ROOT}/../.." && pwd)/alloy/snmp/${name}"
    [[ -f "${sibling}" ]] && src="${sibling}"
  fi
  if [[ -z "${src}" ]]; then
    return 0
  fi
  # Always refresh when source is newer or larger — a stale tiny
  # alloy/snmp-network.yml bind-mount will hide the full library in the image.
  if [[ ! -f "${dest}" ]] || [[ "${src}" -nt "${dest}" ]] || [[ $(stat -c%s "${src}" 2>/dev/null || echo 0) -gt $(stat -c%s "${dest}" 2>/dev/null || echo 0) ]]; then
    cp -f "${src}" "${dest}"
    echo "==> refreshed ${name} from ${src}"
  fi
}

copy_from_lib "${SNMP_YML}" "snmp-network.yml"
copy_from_lib "${FP_YML}" "fingerprinters.yml"
if [[ ! -f "${SNMP_YML}" ]]; then
  cat > "${SNMP_YML}" <<'EOF'
auths:
  public_v2:
    community: public
    version: 2
modules: {}
EOF
fi
if [[ ! -f "${FP_YML}" ]]; then
  cat > "${FP_YML}" <<'EOF'
fingerprinters:
  network:
    probe_oids: ["1.3.6.1.2.1.1.2.0", "1.3.6.1.2.1.1.5.0"]
    default_modules: ["if_mib"]
    matchers: []
EOF
fi
if [[ ! -f "${TARGETS_YML}" ]]; then
  echo '[]' > "${TARGETS_YML}"
  echo "==> seeded empty ${TARGETS_YML} (run make alloy-snmp-discover)"
fi
if [[ ! -f "${TARGETS_COLD_YML}" ]]; then
  echo '[]' > "${TARGETS_COLD_YML}"
fi
if [[ ! -f "${TARGETS_TOPO_YML}" ]]; then
  echo '[]' > "${TARGETS_TOPO_YML}"
fi
DISC_YML="${ROOT}/alloy/snmp-discovery.yml"
if [[ ! -f "${DISC_YML}" ]]; then
  cat > "${DISC_YML}" <<'EOF'
groups:
  - name: pending
    cidrs: ["127.0.0.1/32"]
    auths: ["public_v2"]
    fingerprinter: network
EOF
fi
if [[ ! -f "${ROOT}/alloy/snmp-overrides.yml" ]]; then
  echo 'overrides: []' > "${ROOT}/alloy/snmp-overrides.yml"
fi

enabled=0
case "${LAB_ALLOY_SNMP:-0}" in
  1|true|yes|on|TRUE|YES|ON) enabled=1 ;;
esac
# When Fleet owns the SNMP River, keep local file as a stub (avoid duplicate components).
fleet_snmp=0
case "${LAB_ALLOY_FLEET_SNMP:-0}" in
  1|true|yes|on|TRUE|YES|ON) fleet_snmp=1 ;;
esac
topo=0
case "${LAB_ALLOY_SNMP_TOPOLOGY:-0}" in
  1|true|yes|on|TRUE|YES|ON) topo=1 ;;
esac

# Intervals (lab defaults; raise cold toward 30m for fleet).
HOT_INTERVAL="${LAB_ALLOY_SNMP_HOT_INTERVAL:-60s}"
COLD_INTERVAL="${LAB_ALLOY_SNMP_COLD_INTERVAL:-5m}"
TOPO_INTERVAL="${LAB_ALLOY_SNMP_TOPOLOGY_INTERVAL:-15m}"
HOT_TIMEOUT="${LAB_ALLOY_SNMP_HOT_TIMEOUT:-55s}"
COLD_TIMEOUT="${LAB_ALLOY_SNMP_COLD_TIMEOUT:-4m}"
TOPO_TIMEOUT="${LAB_ALLOY_SNMP_TOPOLOGY_TIMEOUT:-2m}"
SNMP_CONFIG_FILE="${SNMP_TARGETS_DIR}/snmp-network.yml"

{
  echo "// GENERATED by scripts/render-alloy-snmp-scrape.sh — do not edit by hand."
  echo "// Re-run: make generate  (or bash scripts/render-alloy-snmp-scrape.sh)"
  if [[ "${fleet_snmp}" -eq 1 ]]; then
    echo "// LAB_ALLOY_FLEET_SNMP=1 — SNMP scrape owned by Fleet pipeline (network_o11y_alloy_snmp)."
    echo "// Local discovery still writes snmp-targets*.yml; remotecfg delivers the River."
  elif [[ "${enabled}" -eq 0 ]]; then
    echo "// LAB_ALLOY_SNMP=0 — Alloy-native SNMP scrape disabled (ktranslate SNMP unchanged)."
  else
    cat <<EOF
// LAB_ALLOY_SNMP=1 — staggered SNMP scrapes (hot / cold / optional topology).
//
// hot  (${HOT_INTERVAL}): alerting/troubleshooting that fits 60s
//      (if_mib counters + SNMPv2-MIB identity/uptime + CPU/mem + chassis)
// cold (${COLD_INTERVAL}): names/descriptions/MAC (if_mib_meta) + IP inventory (ip_addr)
// topology (LAB_ALLOY_SNMP_TOPOLOGY=1, ${TOPO_INTERVAL}): LLDP/CDP experiments only
// BGP session alerting is traps/syslog — not a scrape interval.
//
// Admin-down interfaces: if_mib filters (ifAdminStatus=up). Not value-based relabel.
// Secrets: SNMP_COMMUNITY / snmp-network.yml auths — never on SD labels.
// Note: Prometheus scrapes are offset within the interval — first cold sample can
// lag up to one full cold interval after Alloy start.

local.file "snmp_targets_hot" {
  filename       = "${SNMP_TARGETS_DIR}/snmp-targets.yml"
  detector       = "poll"
  poll_frequency = "15s"
}

local.file "snmp_targets_cold" {
  filename       = "${SNMP_TARGETS_DIR}/snmp-targets-cold.yml"
  detector       = "poll"
  poll_frequency = "15s"
}

prometheus.exporter.snmp "fabric_hot" {
  config_file           = "${SNMP_CONFIG_FILE}"
  config_merge_strategy = "replace"
  targets               = encoding.from_yaml(local.file.snmp_targets_hot.content)
}

prometheus.exporter.snmp "fabric_cold" {
  config_file           = "${SNMP_CONFIG_FILE}"
  config_merge_strategy = "replace"
  targets               = encoding.from_yaml(local.file.snmp_targets_cold.content)
}

prometheus.relabel "alloy_snmp_hot" {
  forward_to = [otelcol.receiver.prometheus.alloy_snmp.receiver]

  rule {
    target_label = "job"
    replacement  = "alloy-snmp"
  }

  rule {
    target_label = "collector"
    replacement  = "alloy-fleet-lab"
  }

  rule {
    target_label = "snmp_tier"
    replacement  = "hot"
  }

  // snmp_exporter DisplayString names the label after the metric. Copy to sysName.
  rule {
    source_labels = ["snmp_device_info"]
    regex         = "(.+)"
    target_label  = "sysName"
  }

  rule {
    regex  = "snmp_device_info|snmp_scalar_index|exported_sysObjectID"
    action = "labeldrop"
  }
}

prometheus.relabel "alloy_snmp_cold" {
  forward_to = [otelcol.receiver.prometheus.alloy_snmp.receiver]

  rule {
    target_label = "job"
    replacement  = "alloy-snmp"
  }

  rule {
    target_label = "collector"
    replacement  = "alloy-fleet-lab"
  }

  rule {
    target_label = "snmp_tier"
    replacement  = "cold"
  }
}

prometheus.scrape "alloy_snmp_hot" {
  targets         = prometheus.exporter.snmp.fabric_hot.targets
  scrape_interval = "${HOT_INTERVAL}"
  scrape_timeout  = "${HOT_TIMEOUT}"
  forward_to      = [prometheus.relabel.alloy_snmp_hot.receiver]
}

prometheus.scrape "alloy_snmp_cold" {
  targets         = prometheus.exporter.snmp.fabric_cold.targets
  scrape_interval = "${COLD_INTERVAL}"
  scrape_timeout  = "${COLD_TIMEOUT}"
  forward_to      = [prometheus.relabel.alloy_snmp_cold.receiver]
}

otelcol.receiver.prometheus "alloy_snmp" {
  output {
    metrics = [otelcol.processor.transform.preprocessing.input]
  }
}
EOF
    if [[ "${topo}" -eq 1 ]]; then
      cat <<EOF

local.file "snmp_targets_topology" {
  filename       = "${SNMP_TARGETS_DIR}/snmp-targets-topology.yml"
  detector       = "poll"
  poll_frequency = "15s"
}

prometheus.exporter.snmp "fabric_topology" {
  config_file           = "${SNMP_CONFIG_FILE}"
  config_merge_strategy = "replace"
  targets               = encoding.from_yaml(local.file.snmp_targets_topology.content)
}

prometheus.relabel "alloy_snmp_topology" {
  forward_to = [otelcol.receiver.prometheus.alloy_snmp.receiver]

  rule {
    target_label = "job"
    replacement  = "alloy-snmp"
  }

  rule {
    target_label = "collector"
    replacement  = "alloy-fleet-lab"
  }

  rule {
    target_label = "snmp_tier"
    replacement  = "topology"
  }
}

prometheus.scrape "alloy_snmp_topology" {
  targets         = prometheus.exporter.snmp.fabric_topology.targets
  scrape_interval = "${TOPO_INTERVAL}"
  scrape_timeout  = "${TOPO_TIMEOUT}"
  forward_to      = [prometheus.relabel.alloy_snmp_topology.receiver]
}
EOF
    else
      echo "// LAB_ALLOY_SNMP_TOPOLOGY=0 — LLDP/CDP topology scrape disabled."
    fi
  fi
} > "${OUT}"

echo "==> wrote ${OUT} (LAB_ALLOY_SNMP=${LAB_ALLOY_SNMP:-0} FLEET_SNMP=${LAB_ALLOY_FLEET_SNMP:-0} TOPOLOGY=${LAB_ALLOY_SNMP_TOPOLOGY:-0} hot=${HOT_INTERVAL} cold=${COLD_INTERVAL})"
