#!/usr/bin/env bash
# Render alloy/snmp-trap.generated.alloy
#
# LAB_ALLOY_SNMPTRAP=1 — otelcol.receiver.snmptrap on :1620
# LAB_ALLOY_SYSLOG=1   — otelcol.receiver.syslog on :1514 (protocol=none)
# Both join device_name from snmp-targets.yml (file-SD catalog).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/alloy/snmp-trap.generated.alloy"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "${ROOT}/.env" | awk -F= '
    /^[[:space:]]*#/ || NF<2 { next }
    {
      key=$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key != "" && !(key in ENVIRON && ENVIRON[key] != "")) print
    }
  ')
  set +a
fi

mkdir -p "${ROOT}/alloy" "${ROOT}/fixtures/alloy-snmp/mibs"
bash "${ROOT}/scripts/stage-alloy-mibs.sh" || true

# Compose bind-mounts catalog at /etc/alloy. k3s hostPath is /snmp-sd.
SNMP_TARGETS_DIR="${ALLOY_SNMP_TARGETS_DIR:-/etc/alloy}"

enabled_trap=0
case "${LAB_ALLOY_SNMPTRAP:-0}" in
  1|true|TRUE|yes|YES|on|ON) enabled_trap=1 ;;
esac
enabled_syslog=0
case "${LAB_ALLOY_SYSLOG:-0}" in
  1|true|TRUE|yes|YES|on|ON) enabled_syslog=1 ;;
esac
fleet_events=0
case "${LAB_ALLOY_FLEET_EVENTS:-0}" in
  1|true|TRUE|yes|YES|on|ON) fleet_events=1 ;;
esac

{
  echo "// GENERATED by scripts/render-alloy-snmp-trap.sh — do not edit by hand."
  echo "// Re-run: make generate  (or bash scripts/render-alloy-snmp-trap.sh)"
  echo ""
  if [[ "${fleet_events}" == "1" ]]; then
    echo "// LAB_ALLOY_FLEET_EVENTS=1 — traps/syslog owned by Fleet pipeline (network_o11y_alloy)."
    echo "// Query: {service_name=\"alloy-snmptrap\"} / {service_name=\"alloy-syslog\"}"
  elif [[ "${enabled_trap}" != "1" && "${enabled_syslog}" != "1" ]]; then
    echo "// LAB_ALLOY_SNMPTRAP=0 LAB_ALLOY_SYSLOG=0 — Alloy trap/syslog receivers disabled."
  else
    cat <<EOF
// Device catalog for trap/syslog join (same YAML as Alloy SNMP scrape).
local.file "device_join_catalog" {
  filename       = "${SNMP_TARGETS_DIR}/device-join.yml"
  detector       = "poll"
  poll_frequency = "15s"
}

EOF
    if [[ "${enabled_trap}" == "1" ]]; then
      cat <<'EOF'
// LAB_ALLOY_SNMPTRAP=1 — SNMP traps/informs as OTel logs (experimental).
// Query: {service_name="alloy-snmptrap"}

otelcol.receiver.snmptrap "lab" {
  listen_address = "0.0.0.0:1620"
  mib_paths      = ["/etc/alloy/mibs"]
  targets        = encoding.from_yaml(local.file.device_join_catalog.content)
  attributes     = {
    job       = "snmptrap",
    collector = "alloy-snmptrap",
  }

  output {
    logs = [otelcol.processor.transform.snmptrap_logs.input]
  }
}

otelcol.processor.transform "snmptrap_logs" {
  error_mode = "ignore"

  log_statements {
    context = "resource"
    statements = [
      `set(attributes["collector"], "alloy-snmptrap")`,
      `set(attributes["service.name"], "alloy-snmptrap")`,
    ]
  }

  output {
    logs = [otelcol.processor.resourcedetection.default.input]
  }
}

EOF
    fi
    if [[ "${enabled_syslog}" == "1" ]]; then
      cat <<'EOF'
// LAB_ALLOY_SYSLOG=1 — device syslog as OTel logs.
// Query: {service_name="alloy-syslog"}
// protocol=none keeps vendor/non-RFC bodies; PRI still decodes when present.
// on_error=send (default) never drops a failed parse.

otelcol.receiver.syslog "lab" {
  protocol              = "none"
  allow_skip_pri_header = true
  on_error              = "send"
  targets               = encoding.from_yaml(local.file.device_join_catalog.content)

  udp {
    listen_address = "0.0.0.0:1514"
    add_attributes = true
  }

  output {
    logs = [otelcol.processor.transform.syslog_logs.input]
  }
}

otelcol.processor.transform "syslog_logs" {
  error_mode = "ignore"

  log_statements {
    context = "log"
    statements = [
      `set(attributes["severity"], severity_text) where severity_text != ""`,
      `set(attributes["job"], "syslog")`,
    ]
  }

  log_statements {
    context = "resource"
    statements = [
      `set(attributes["collector"], "alloy-syslog")`,
      `set(attributes["service.name"], "alloy-syslog")`,
    ]
  }

  output {
    logs = [otelcol.processor.resourcedetection.default.input]
  }
}

EOF
    fi
  fi
} > "${OUT}"

echo "==> wrote ${OUT} (LAB_ALLOY_SNMPTRAP=${LAB_ALLOY_SNMPTRAP:-0} LAB_ALLOY_SYSLOG=${LAB_ALLOY_SYSLOG:-0} FLEET_EVENTS=${LAB_ALLOY_FLEET_EVENTS:-0})"
