#!/usr/bin/env bash
# Render Alloy OTLP export block (1 or 2 Grafana Cloud sinks).
# Dual-ship when GC_OTLP_URL_2 + GC_OTLP_ACCOUNT_2 + GC_OTLP_KEY_2 are set in local/.env.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/alloy/otlp-export.generated.alloy"
ENV_FILE="${REPO_ROOT}/.env"

GC_OTLP_URL_2=""
GC_OTLP_ACCOUNT_2=""
GC_OTLP_KEY_2=""
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a
  # shellcheck disable=SC1091
  source <(sed 's/\r$//' "$ENV_FILE")
  set +a
fi

dual=0
if [[ -n "${GC_OTLP_URL_2:-}" && -n "${GC_OTLP_ACCOUNT_2:-}" && -n "${GC_OTLP_KEY_2:-}" ]]; then
  dual=1
fi

{
  echo "// GENERATED by scripts/render-alloy-otlp-export.sh — do not edit by hand."
  echo "// Re-run: make generate  (or bash scripts/render-alloy-otlp-export.sh)"
  echo "// Dual OTLP sinks: ${dual} (set GC_OTLP_*_2 in .env to fan-out to a second stack)."
  echo ""
  cat <<'EOF'
otelcol.processor.batch "default" {
  output {
EOF
  if [[ "$dual" -eq 1 ]]; then
    cat <<'EOF'
    metrics = [
      otelcol.exporter.otlphttp.grafana_cloud.input,
      otelcol.exporter.otlphttp.grafana_cloud_2.input,
    ]
    logs = [
      otelcol.exporter.otlphttp.grafana_cloud.input,
      otelcol.exporter.otlphttp.grafana_cloud_2.input,
    ]
    traces = [
      otelcol.exporter.otlphttp.grafana_cloud.input,
      otelcol.exporter.otlphttp.grafana_cloud_2.input,
    ]
EOF
  else
    cat <<'EOF'
    metrics = [otelcol.exporter.otlphttp.grafana_cloud.input]
    logs    = [otelcol.exporter.otlphttp.grafana_cloud.input]
    traces  = [otelcol.exporter.otlphttp.grafana_cloud.input]
EOF
  fi
  cat <<'EOF'
  }
}

otelcol.exporter.otlphttp "grafana_cloud" {
  client {
    endpoint = env("GC_OTLP_URL")
    auth     = otelcol.auth.basic.grafana_cloud.handler
  }
}

otelcol.auth.basic "grafana_cloud" {
  username = env("GC_OTLP_ACCOUNT")
  password = env("GC_OTLP_KEY")
}
EOF
  if [[ "$dual" -eq 1 ]]; then
    cat <<'EOF'

otelcol.exporter.otlphttp "grafana_cloud_2" {
  client {
    endpoint = env("GC_OTLP_URL_2")
    auth     = otelcol.auth.basic.grafana_cloud_2.handler
  }
}

otelcol.auth.basic "grafana_cloud_2" {
  username = env("GC_OTLP_ACCOUNT_2")
  password = env("GC_OTLP_KEY_2")
}
EOF
  fi
} >"${OUT}"

echo "wrote ${OUT} (dual=${dual})"
