#!/usr/bin/env bash
# Resolve KTRANS_HOST (explicit .env override or machine hostname) and write
# compose-host.generated.env for docker compose interpolation.
#
# make generate runs this so every compose path — make targets and scripts —
# gets the same deployment.host / OTEL_SERVICE_NAME suffix without hardcoding
# the hostname in .env.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/compose-host.generated.env"
KTRANS_HOST="$(bash "${REPO_ROOT}/scripts/host-id.sh")"

{
  echo "# GENERATED by scripts/write-compose-host-env.sh — do not edit by hand."
  echo "# Re-run: make generate  (or bash scripts/write-compose-host-env.sh)"
  printf 'KTRANS_HOST=%s\n' "${KTRANS_HOST}"
} > "${OUT}"
