apiVersion: syntheticmonitoring.ext.grafana.app/v1alpha1
kind: Check
metadata:
  name: net-o11y-alb-ecs-demo-http
spec:
  job: net-o11y-alb-ecs-demo-http
  target: http://ecs-demo-alb-536646715.us-east-1.elb.amazonaws.com/
  frequency: 60000
  timeout: 10000
  enabled: true
  labels:
    - name: project
      value: network-o11y-demo
    - name: target_type
      value: alb
  probes:
    - Ohio
    - NorthVirginia
    - network-o11y-colocated-ec2
    - network-o11y-laptop-wsl
  settings:
    http:
      method: GET
      validStatusCodes: [200, 301, 302, 403, 404, 503]
